class EngDialogs {
	String word;
	EngDialogs();
	static getList(){
		List<String> lst = [];
		lst.add("Joyce, I'd like you to meet Victor. ");
		lst.add("Joyce Gold-Victor Danin");
		lst.add("How do you do?");
		lst.add("Hello. It's a pleasure to meet you");
		lst.add("Victor is a friend of Frank's ");
		lst.add("He arrived in New York a couple of weeks ago");
		lst.add("Oh, where are you from?");
		lst.add("I'm from Moscow");
		lst.add("Moscow, USSR? ");
		lst.add("You know, in America there are several towns named Moscow. ");
		lst.add("Are you an immigrant or are you just visiting relatives?");
		lst.add("I'm going to stay for good. ");
		lst.add("It took me eight years to get my exit visa");
		lst.add("Excuse me. ");
		lst.add("There are the Millers. ");
		lst.add("I must say hello to them");
		lst.add("How do you like America?");
		lst.add("I like it very much here. ");
		lst.add("But for the time being, I've a lot of problems");
		lst.add("Have you come with your family?");
		lst.add("Yes, I have. With my wife and my son");
		lst.add("What are your most urgent problems?");
		lst.add("First of all. I've to get a job");
		lst.add("What's your occupation?");
		lst.add("I'm electrical engineer. My wife is a draftsperson");
		lst.add("Maybe I can help you to find a job. ");
		lst.add("I'm with an employment agency. ");
		lst.add("Here is my card. ");
		lst.add("Call me on Tuesday morning if it's convenient for you");
		lst.add("What's the best time to call you?");
		lst.add("After 10 AM");
		lst.add("Thank you so much. ");
		lst.add("I will certainly call you");
		lst.add("Your English sounds fine");
		lst.add("Americans usually say that. ");
		lst.add("They are just polite");
		lst.add("We want to encourage you. ");
		lst.add("You explain things pretty well. ");
		lst.add("You are going to make it -no doubt");
		lst.add("Thank you. You are very kind");
		lst.add("It's getting late. ");
		lst.add("I guess you don't have a car yet. ");
		lst.add("I'd be glad to give you a ride");
		lst.add("I'd appreciate it very much.");
		lst.add("Useful Expressions ");
		lst.add("with pleasure ");
		lst.add("I fully agree ");
		lst.add("I hope we'll meet again ");
		lst.add("what a pity ");
		lst.add("whenever you like would you be so kind ");
		lst.add("just a minute ");
		lst.add("just a moment ");
		lst.add("nice meeting you");
		lst.add("ASKING FOR DIRECTIONS");
		lst.add("Pardon me, sir. ");
		lst.add("Could you tell me how to get to the bus terminal?");
		lst.add("Turn left at the corner");
		lst.add("Thank you");
		lst.add("You are welcome");
		lst.add("I beg your pardon. ");
		lst.add("Where's the nearest subway station?");
		lst.add("It's right down the street");
		lst.add("it's three blocks from here");
		lst.add("it's at the second corner");
		lst.add("it's at the next corner");
		lst.add("What's the best way of getting to your place?");
		lst.add("Take the subway. ");
		lst.add("Get off at Lincoln Center, turn right and walk two blocks");
		lst.add("Good afternoon. ");
		lst.add("I'd like to ask you how to get to Brooklyn College? ");
		lst.add("Where are you starting from?");
		lst.add("At Jackson Heights");
		lst.add("Roosevelt Avenue?");
		lst.add("That's correct");
		lst.add("Take train number 7, get off at Times Square and transfer there to train number 2. ");
		lst.add("Get off at the last stop");
		lst.add("Is Brooklyn College within walking distance from there?");
		lst.add("Yes, it is");
		lst.add("Thank you");
		lst.add("You are welcome. ");
		lst.add("Alexander can't find his way to Edward's home. ");
		lst.add("Edward gives him directions on the phone");
		lst.add("Hi, Alexander. Where are you? ");
		lst.add("At the corner of Taylor Avenue and Duke Street? ");
		lst.add("Wait there. ");
		lst.add("I'll be there in five minutes");
		lst.add("It's not necessary. ");
		lst.add("I drove the car from New Haven. ");
		lst.add("Give me the directions. I'll find my way");
		lst.add("All right. ");
		lst.add("Go north on Duke Street to Shore Drive. ");
		lst.add("You can't miss the large supermarket there. ");
		lst.add("Turn left there. ");
		lst.add("Continue on Stevenson Avenue to Fourth Street. ");
		lst.add("Make a right turn and go to the middle of the block. ");
		lst.add("I'll wait for you in front of the house");
		lst.add("I got it. See you soon, Edward");
		lst.add("I'm afraid we're lost");
		lst.add("We'd better ask for directions");
		lst.add("Okay. I'll ask at the next gas station. Stopping in front of a gas station:");
		lst.add("How do we get to York Village?");
		lst.add("You're going west, but you should be going east");
		lst.add("Should we make a U-turn?");
		lst.add("Yes. Make a U-turn and go straight. ");
		lst.add("Then turn to the right at the traffic lights. ");
		lst.add("That's interstate 95. ");
		lst.add("Take interstate 95 for about 15 miles and then get off at Roundview. ");
		lst.add("You can't miss your destination");
		lst.add("Thank you very much");
		lst.add("RIDING THE BUS");
		lst.add("Pardon me, do the buses stop here?");
		lst.add("YES, most downtown buses stop at this corner");
		lst.add("I want to go to Washington Avenue. Can I take any bus that stops here?");
		lst.add("You can take any bus except number 12. The number 12 turns off at Richmond Street");
		lst.add("How often do the buses run?");
		lst.add("They are supposed to run according to the schedule that you can see over there. ");
		lst.add("In fact, the buses don't always run on schedule");
		lst.add("What are the usual intervals between the bus arrivals?");
		lst.add("About every fifteen minutes. ");
		lst.add("You won't have to wait any longer. ");
		lst.add("A bus is coming. ");
		lst.add("It's number 5. ");
		lst.add("You can take it");
		lst.add("A transfer, please.");
		lst.add("Driver giving a transfer");
		lst.add("How much is the fare?");
		lst.add("One dollar");
		lst.add("Will you accept a dollar bill?");
		lst.add("No. Only exact change is accepted coins or tokens. ");
		lst.add("Stand back from the door. ");
		lst.add("Move to the rear. Let the passengers off");
		lst.add("I'm afraid of missing the public library");
		lst.add("Which one?");
		lst.add("The library on Washington Avenue");
		lst.add("Okay. I'll tell you when you've to get off. ");
		lst.add("Several minutes later");
		lst.add("Get off at the next stop. ");
		lst.add("Cross the street. ");
		lst.add("It's a big building. ");
		lst.add("You can't miss the library there");
		lst.add("Would you point out the City Theater as we go by?");
		lst.add("It's on Third Avenue. ");
		lst.add("It's the next stop");
		lst.add("Thank you. ");
		lst.add("At the stop");
		lst.add("Move along, please. ");
		lst.add("There are many people waiting to get on. ");
		lst.add("That's it. I'm closing the door. ");
		lst.add("Another bus will be along in about five minutes");
		lst.add("LOOKING FOR AN APARTMENT");
		lst.add("Oceanfront Realty. Bob Murphy speaking");
		lst.add("Hello. My name is Boris Koltunov. ");
		lst.add("I'm calling about the ad");
		lst.add("Which one?");
		lst.add("The two-bedroom apartment. ");
		lst.add("How much is the rent");
		lst.add("700 a month. ");
		lst.add("You have also to pay a 700 dollar deposit that will be given back to you when you move.");
		lst.add("The agency's fee amounts to one month rent");
		lst.add("Is there a lease to be signed?");
		lst.add("Yes, there is. It's a two-year lease");
		lst.add("When can I see the apartment?");
		lst.add("You can see it today after three o'clock");
		lst.add("What about four o'clock? Is that all right?");
		lst.add("Okay. I'll meet you at the apartment. ");
		lst.add("240 Beach Street, Apt. 5A");
		lst.add("That's fine, thanks");
		lst.add("This is the living room");
		lst.add("It's rather large. ");
		lst.add("What about bedrooms?");
		lst.add("Let's have a look at them. ");
		lst.add("They have a beautiful ocean view");
		lst.add("How many closets are there?");
		lst.add("Two clothes closets and a linen closet");
		lst.add("Where is the bathroom?");
		lst.add("He opens the door to the bathroom.");
		lst.add("It has a shower and a bathtub. ");
		lst.add("Now let's go to the kitchen. ");
		lst.add("As you can see it's modern. ");
		lst.add("It has a new sink and stove. ");
		lst.add("There's space for a dishwasher. ");
		lst.add("The refrigerator is brand new. ");
		lst.add("Do you like the apartment?");
		lst.add("Yes, I do. Unfortunately the rent is rather high");
		lst.add("You won't find anything cheaper in this neighborhood");
		lst.add("I'll think it over. Thank you");
		lst.add("You are welcome.");
		lst.add("I'd like to rent the apartment you showed me two days ago. ");
		lst.add("Is it still available?");
		lst.add("Yes, it is");
		lst.add("I'll take the apartment. I like it");
		lst.add("Okay. You can sign the lease in my office");
		lst.add("AT THE SUPERMARKET");
		lst.add("Do you have the shopping list?");
		lst.add("Yes it's in my pocket. ");
		lst.add("I'll get a cart. ");
		lst.add("We'll shop together. ");
		lst.add("We need laundry detergent");
		lst.add("Is the big size too expensive?");
		lst.add("Not at all. ");
		lst.add("It makes sense to buy a big box of detergent. ");
		lst.add("You save about a penny for every ounce");
		lst.add("How come?");
		lst.add("You've to read not only the price for the item but also the price for it by weight and volume. ");
		lst.add("It's cheaper to buy big sizes, especially for staples that are used for a longer period of time");
		lst.add("I'll keep it in mind. What's the next on the shopping list?");
		lst.add("Orange juice");
		lst.add("There are a lot of various brands of them");
		lst.add("The store's own brand is the least expensive one. ");
		lst.add("The quality is the same, but it's a bit cheaper");
		lst.add("Do big supermarkets have their own brands of other things?");
		lst.add("Yes. Always look for the store's own brands. ");
		lst.add("What about apples?");
		lst.add("Apples are in aisle eight");
		lst.add("How much are they?");
		lst.add("They're 84 cents a pound");
		lst.add("What do we look for next?");
		lst.add("Let's get to the meat counter");
		lst.add("Okay. I think we need a chicken and some veal. I'll get both items");
		lst.add("Don't forget to look at the date on the label");
		lst.add("It's February twenty third for the chicken, and twenty second for the veal");
		lst.add("That's okay. Today is February nineteenth");
		lst.add("What does the date mean?");
		lst.add("The date indicates the last day the store is supposed to sell this item");
		lst.add("Which foods are dated?  ");
		lst.add("If foods are perishable, they've to be dated.");
		lst.add("You are an experienced buyer. What else do we need?");
		lst.add("I've to check the shopping list. ");
		lst.add("We need half a pound of butter, sour cream, and eggs.");
		lst.add("Dairy products are in aisle 3");
		lst.add("All right. Here are the eggs. ");
		lst.add("I prefer unsalted butter. ");
		lst.add("Would you get it?");
		lst.add("I got butter and sour cream");
		lst.add("Now we've to buy coffee. That's in aisle 5");
		lst.add("I've cut out an ad from the paper. ");
		lst.add("There are special prices they've advertised for instant coffee.");
		lst.add("Okay. Get the coffee that was advertised. ");
		lst.add("That's all we need. ");
		lst.add("Let's go to the cash register ");
		lst.add("SHOPPING FOR CLOTHING");
		lst.add("Can you help me, please?");
		lst.add("Yes, sir. What is it?");
		lst.add("I'm looking for a flannel suit, size 40");
		lst.add("What color do you want?");
		lst.add("I prefer something in gray");
		lst.add("Here's an excellent suit in gray flannel. Will you try it on?");
		lst.add("Yes, I will. Where is the fitting room?");
		lst.add("Come this way");
		lst.add("How does it look?");
		lst.add("It looks great. It's exactly your size");
		lst.add("How much is it?");
		lst.add("This suit is on sale. It's only 115 dollars");
		lst.add("All right. I'll take it");
		lst.add("May I help you?");
		lst.add("Yes, I'm looking for a blouses");
		lst.add("What's your size?");
		lst.add("I wear size 12. ");
		lst.add("Could you show me some blouses in solid color?");
		lst.add("What colors do you want?");
		lst.add("Yellow and white");
		lst.add("They are over here");
		lst.add("What's the material?");
		lst.add("It's fifty percent cotton and fifty percent polyester");
		lst.add("This white blouse looks nice. I'd like to try it on");
		lst.add("The fitting room is to your left");
		lst.add("I think this blouse is all right");
		lst.add("Very well, madam. ");
		lst.add("Will that be cash or credit card?");
		lst.add("I'd like to give you a check");
		lst.add("We need at least one piece of identification");
		lst.add("Here is my driver's license");
		lst.add("All right. We can accept your check");
		lst.add("These shoes are pretty. ");
		lst.add("What colors do they come in?");
		lst.add("Presently we have them in brown and black");
		lst.add("Could you show me the black shoes in a medium heel?");
		lst.add("We have them in a higher, lower, and medium heel. ");
		lst.add("Just a minute. ");
		lst.add("I'll bring you the pair you wanted to see. ");
		lst.add("Yesterday I bought this skirt. ");
		lst.add("I'd like a refund. ");
		lst.add("Do you have the receipt with you?");
		lst.add("Yes, I do");
		lst.add("You'll get your refund in room 208, on the second floor");
		lst.add("A JOB VACANCY");
		lst.add("Victor was watching TV when the telephone rang. ");
		lst.add("It was his American friend Dick Jones");
		lst.add("Victor, I hope I'm not calling too late");
		lst.add("No, Dick. I was watching television. ");
		lst.add("How are you?");
		lst.add("I am fine. ");
		lst.add("I'm calling you at such a late hour because there is good news for you. ");
		lst.add("An hour ago, I spoke to a friend of mine. ");
		lst.add("He's on the board of directors at 'A & B Instrument Company'. ");
		lst.add("They have an immediate opening for a software programmer. ");
		lst.add("They are looking for a specialist in this field. ");
		lst.add("I told my friend about you. ");
		lst.add("He wants to know if you can come tomorrow for an interview. ");
		lst.add("You shouldn't miss this opportunity");
		lst.add("Dick, you are absolutely right. ");
		lst.add("I agree with you completely. ");
		lst.add("I realize that I should see the interviewer");
		lst.add("but what about my job at the gas station?'");
		lst.add("Oh, come on. ");
		lst.add("Don't tell them where you are going. ");
		lst.add("Just tell your supervisor you have some personal business to attend to. ");
		lst.add("Promise him to make up the time");
		lst.add("That makes sense, Dick. ");
		lst.add("But I'm a bit afraid because of my poor English");
		lst.add("Stop worrying about it. ");
		lst.add("All you have to do is to explain your previous experience. ");
		lst.add("You can do it perfectly well. ");
		lst.add("You've to show your experience but not English stylistic subtleties. ");
		lst.add("Even a few grammatical errors won't harm you. ");
		lst.add("I'm sure you'll feel at ease with the interviewer");
		lst.add("I hope so. ");
		lst.add("But I'm still confused about the use of English tenses. ");
		lst.add("Nevertheless I've made up my mind. ");
		lst.add("I'm going to see the interviewer");
		lst.add("Okay. Would you write down the address?");
		lst.add("All right. I'm listening");
		lst.add("620 Broadway, 25th floor. ");
		lst.add("Ask for personnel. ");
		lst.add("Don't leave home without your resume. ");
		lst.add("Good luck");
		lst.add("Thank you, Dick");
		lst.add("BUSINESS CALLS");
		lst.add("Good morning. May I speak to Mr. Wood?");
		lst.add("He is not in right now. Who is calling, please?");
		lst.add("This is Boris Rudakov. ");
		lst.add("I have a letter from Mr. Wood asking me to call him for an interview appointment. ");
		lst.add("He has my resume");
		lst.add("I see. ");
		lst.add("Mr. Wood is out to lunch right now (in a meeting right now), but I expect him back very shortly");
		lst.add("At what time would you suggest that I call back?");
		lst.add("He usually gets back to the office about two o'clock. ");
		lst.add("May be it would be better if I have him call you? ");
		lst.add("What's your telephone number?");
		lst.add("718-459-3243");
		lst.add("Thank you, Mr. Rudakov. ");
		lst.add("As soon as he's back, he will return your call");
		lst.add("Thank you");
		lst.add("Good-bye");
		lst.add("Good morning");
		lst.add("Could I speak to Peter Orlov? ");
		lst.add("Speaking");
		lst.add("This is Mary Thomas of Metro Data Control. ");
		lst.add("I'm Mr. Dillon's secretary. ");
		lst.add("He's interested in your letter and resume and would like to see you");
		lst.add("Fine. I would like very much to speak to him");
		lst.add("Let's set up an interview appointment");
		lst.add("Okay");
		lst.add("How about tomorrow at 10 AM?");
		lst.add("That's Okay with me");
		lst.add("We are located on 516 Fifth Avenue, 7th floor. ");
		lst.add("Do you know how to get there?");
		lst.add("Yes, I hope so. ");
		lst.add("I guess I can take the F train. ");
		lst.add("Where should I get off?");
		lst.add("You should get off at 42nd Street. ");
		lst.add("From there you can walk. ");
		lst.add("It will take you not more than five minutes to get to our place");
		lst.add("Would you mind repeating the address?");
		lst.add("516 Fifth Avenue. 7th floor. ");
		lst.add("Ask for personnel");
		lst.add("Thank you");
		lst.add("You are welcome. See you tomorrow morning");
		lst.add("USEFUL EXPRESSIONS");
		lst.add("Do you follow me? ");
		lst.add("Are you with me?");
		lst.add("Will you leave a message?");
		lst.add("Can I take a message?");
		lst.add("I'll call you right back.");
		lst.add("There's a telephone call for you.");
		lst.add("Don't talk so fast");
		lst.add("May I use your telephone?");
		lst.add("Please dial again.");
		lst.add("Can you speak a bit louder? I can't hear you.");
		lst.add("I'll get it.");
		lst.add("You have the wrong number.");
		lst.add("What number are you calling?");
		lst.add("What number did you dial?");
		lst.add("What's your extension?");
		lst.add("Please pick up the receiver.");
		lst.add("Somebody has hung up.");
		lst.add("The telephone is out of order.");
		lst.add("My office number is...");
		lst.add("My home number is...");
		lst.add("I'm returning your phone call");
		lst.add("PREPARING A RESUME");
		lst.add("I'm pleased to meet you, Peter. ");
		lst.add("My sister Linda has often spoken about you");
		lst.add("I'm happy to meet you, Jack");
		lst.add("So you're a newcomer from Russia. ");
		lst.add("How long have you been in New York?");
		lst.add("I've been living here about 10 months");
		lst.add("Do you like living here?");
		lst.add("Yes, I do. New York is a fascinating city");
		lst.add("Do you have a job?");
		lst.add("Yes, I do. But that is a sad story. ");
		lst.add("I'm an electronics engineer without American experience. ");
		lst.add("Now I'm a cab driver");
		lst.add("Don't loose heart. ");
		lst.add("Driving a cab is not what you have dreamed of. ");
		lst.add("But if you have a good professional background, sooner or later you will get a job in your special field. ");
		lst.add("Do you have a resume?");
		lst.add("Yes, I do. I have it with me");
		lst.add("Could you show it to me? ");
		lst.add("I happened to work for the personnel department of a large company");
		lst.add("Here it is.");
		lst.add("That kind of resume won't get you a high-level job. ");
		lst.add("Major companies receive about 300 resumes a week. ");
		lst.add("They ignore 290 of them");
		lst.add("What's the reason for it?");
		lst.add("Many job hunters stress details that don't count. ");
		lst.add("In this resume of yours, these long Russian words and names are rather confusing for an American employer");
		lst.add("But my resume should reflect professional experience, shouldn't it?");
		lst.add("Yes, of course. ");
		lst.add("You describe yourself as an electronics engineer. ");
		lst.add("That's not enough. ");
		lst.add("No doubt, you have advanced knowledge. ");
		lst.add("But what is your objective? ");
		lst.add("What kind of position do you want? ");
		lst.add("What abilities qualify you for a job as an electronics engineer with Manhatten Electronics to name just an example?");
		lst.add("You should tell about your strengths and experiences which will let you do that job. ");
		lst.add("Your strengths should be given more space. ");
		lst.add("Other information should be left out");
		lst.add("Sometimes it's rather difficult to decide what to stress and what to leave out");
		lst.add("An employer's main interest is in what you can do for the company. ");
		lst.add("Include information that shows that you are the right kind of person for the job. ");
		lst.add("Leave out anything that might give an employer reason for passing you by");
		lst.add("But what about the lack of American experience? ");
		lst.add("That's a serious obstacle to getting a job");
		lst.add("If the employer realizes that you are the right man for a particular position he will give you an appointment. ");
		lst.add("I know quite a few Russians who hold top positions. ");
		lst.add("Write another kind of resume and show it to me");
		lst.add("Thank you so much");
		lst.add("You are welcome. ");
		lst.add("Call me as soon as your resume is ready");
		lst.add("PREPARING FOR A JOB INTERVIEW");
		lst.add("Now you have a reasonable resume. ");
		lst.add("By reading it your potential employer can see what abilities qualify you for a job as an electronics engineer. ");
		lst.add("Your job objective is indicated. ");
		lst.add("I hope your revised resume will lead to job interviews");
		lst.add("When thinking of an upcoming interview, I am really scared. ");
		lst.add("My English is not good enough, and I don't know how to behave when being interviewed");
		lst.add("Before going to the interview, try to get information about the company or the job you would like to get into.");
		lst.add("For example, if you have an interview at a large electronics firm, you will make a better impression when you are familiar with articles about that company. ");
		lst.add("Doing anything well takes some information.");
		lst.add("That implies to job hunting too. ");
		lst.add("Any good library has books which will tell you the names of companies in industries of interest to you, as well as the names of people representing those companies");
		lst.add("You are perfectly right, Jack. ");
		lst.add("But how can I overcome my nervousness?");
		lst.add("If you are well informed your confidence is up. ");
		lst.add("You are familiar with the American terminology in your field. ");
		lst.add("You are an experienced specialist. ");
		lst.add("People can tell when you are well prepared. ");
		lst.add("You will be asked questions that you can answer easily. ");
		lst.add("You won't be nervous in an upcoming interview. ");
		lst.add("Your best guide is to rely on your own common sense. ");
		lst.add("There are, however, some common rules for the interviews");
		lst.add("could you give me some examples?");
		lst.add("When greeting the representative of the company, wait until he moves to shake hands. ");
		lst.add("You should also wait until he offers you a seat");
		lst.add("But what about the usual questions people are asked in an interview?");
		lst.add("The most common questions are, for instance");
		lst.add("Why are you interested in joining our company?");
		lst.add("Why do you feel qualified for this job?");
		lst.add("What do you know about the company?");
		lst.add("Do you enjoy working with others? ");
		lst.add("Are you willing to work overtime?");
		lst.add("Tell me about your experience. ");
		lst.add("What can I do for you?");
		lst.add("Are there any surprise questions?");
		lst.add("You should anticipate questions like");
		lst.add("Why should I hire you?");
		lst.add("What are your three greatest strengths for this job?");
		lst.add("I see. These are rather tricky questions. ");
		lst.add("Are there any topics I should avoid discussing with the interviewer?");
		lst.add("In discussing your previous job, avoid criticizing former employers or fellow workers. ");
		lst.add("Don't discuss your personal, domestic or financial problems unless you are specifically asked about them");
		lst.add("If I am offered a job, is it appropriate to ask questions referring to the salary?");
		lst.add("Absolutely. You can state the salary you want, but not until the employer has introduced the subject");
		lst.add("I greatly appreciate your giving me this valuable information");
		lst.add("AT THE POST OFFICE");
		lst.add("Give me 100 first-class stamps, please");
		lst.add("Here you are. That will be 25 dollars. Anything else?");
		lst.add("Yes, I want 20 airmail stamps for Europe");
		lst.add("Okay. Your total bill is 34 dollars");
		lst.add("May I have a receipt?");
		lst.add("Of course");
		lst.add("I also need airmail labels");
		lst.add("All right, sir");
		lst.add("One more question. ");
		lst.add("I want to register this letter. ");
		lst.add("Can I do it at your window?");
		lst.add("No. Go to the second window on your right");
		lst.add("I want to send this letter by registered mail");
		lst.add("You have to fill out this form. ");
		lst.add("Do you want a return receipt?");
		lst.add("What is a return receipt?");
		lst.add("The addressee signs a receipt when he receives a registered letter or a package. ");
		lst.add("This receipt is returned to you by airmail by the Post Office. ");
		lst.add("A return receipt is your proof that the letter was delivered");
		lst.add("Okay. I would like to have a return receipt");
		lst.add("Then you have to fill an additional form that looks like a post card. ");
		lst.add("Come back to this window as soon as you have filled out the forms");
		lst.add("I would like to mail this parcel by fourth class mail");
		lst.add("What's in the parcel?");
		lst.add("Nothing but books. ");
		lst.add("The parcel should be mailed by books rate");
		lst.add("Four pounds. It would cost 1.95");
		lst.add("How long does it take for a parcel to arrive in San Francisco?");
		lst.add("Fourth class mail takes about 15 days to arrive");
		lst.add("Okay, let pays for postage. ");
		lst.add("I have a problem. I'll be out of town next week. ");
		lst.add("Can you hold my mail for me at the post office? ");
		lst.add("I'll pick it up when I get back");
		lst.add("Yes, we can do that. You have to fill out this form. ");
		lst.add("Bring it back to me");
		lst.add("OPENING A SAVINGS ACCOUNT");
		lst.add("Good morning. What can I do for you?");
		lst.add("Good morning. I would like to open a savings account. ");
		lst.add("Could you explain your policy to me?");
		lst.add("A small initial deposit is all it takes to open a savings account at our bank");
		lst.add("But if you open your account with five hundred dollars or more and keep that much at all times, there is no service charge. ");
		lst.add("If you fall below the 500 dollar limit, you will be charged five dollars a month");
		lst.add("I'm not sure I understand what you've said about the five-hundred dollar limit. ");
		lst.add("Could you explain that to me again?");
		lst.add("Of course. Our bank requires you to maintain a minimum balance of 500 dollars or more. ");
		lst.add("Should your minimum balance fall below that amount your account would be charged for 5 dollars  a month");
		lst.add("I see. That's clear enough. ");
		lst.add("One more question");
		lst.add("Go ahead");
		lst.add("How does the bank know what amount to use to figure out my balance? ");
		lst.add("Okay. That's not difficult to understand. ");
		lst.add("Our computer adds all the daily figures and then divides by the number of days in our statement period. ");
		lst.add("That's called your average daily balance");
		lst.add("May I ask you another question?");
		lst.add("I'll be happy to answer your question");
		lst.add("Could I get a banking card after opening an account?");
		lst.add("When you open an account, you will be in touch with your money thanks to our machine services. ");
		lst.add("Our machines can handle the most regular teller transactions. ");
		lst.add("You can make deposits, cash withdrawals, and balance inquiries with your card. ");
		lst.add("The machine is at work 24 hours a day, 7 days a week");
		lst.add("Okay. I've made up my mind. ");
		lst.add("I'd like to open a savings account with a deposit of one thousand dollars");
		lst.add("Could you please fill out this application. ");
		lst.add("Besides you need to write a deposit ticket for 1000 dollars. ");
		lst.add("If you have any questions regarding the application, I'll be glad to assist you. ");
		lst.add("Everything is correct. ");
		lst.add("Here is your passbook. ");
		lst.add("The bank will pay you 5.12% interest. ");
		lst.add("Thank you for your assistance");
		lst.add("OPENING A CHECKING ACCOUNT");
		lst.add("Good afternoon. May I help you?");
		lst.add("Good afternoon. I'm here to open a checking account. ");
		lst.add("My name is Vladimir Melnik. ");
		lst.add("My wife's name is Natalya");
		lst.add("Do you want a joint account with your spouse?");
		lst.add("Yes, I do. ");
		lst.add("Tell me about your checking account policy. ");
		lst.add("Is there a minimum balance required?");
		lst.add("If you open a checking account you are supposed to maintain an average daily balance of 1000 dollars. ");
		lst.add("As long as you keep this average balance you won't be charged for banking services. ");
		lst.add("Should you fall below the 1-thousand-dollar limit, you would have to pay a service charge of 6 dollar a month, and each of your transactions would be charged separately");
		lst.add("What is meant by transaction charge?");
		lst.add("You'll have to pay 25 cents for each check made out by your spouse or you, and also 25 cents for each cash withdrawal. ");
		lst.add("But you can easily avoid paying these charges by maintaining one thousand dollars or more on your checking account");
		lst.add("I'd like to know how much interest you pay");
		lst.add("Interest is paid if your average daily balance is over 2500 dollars. ");
		lst.add("Unless you fall below 2500 dollars, you'll be paid 6% interest.");
		lst.add("We credit the interest you've earned automatically to your account");
		lst.add("I would like to open a checking account with a deposit of 1500 dollars. ");
		lst.add("Is it okay?");
		lst.add("It is perfectly all right. ");
		lst.add("You can order your check books after having filled out an application and your deposit ticket.");
		lst.add("Is anything wrong?");
		lst.add("Everything is correct. ");
		lst.add("Now you can order your check books");
		lst.add("I have a question. ");
		lst.add("What are the preconditions for getting a credit card?");
		lst.add("You must have an income of 15000 dollars or more");
		lst.add("What proof of income will you accept?");
		lst.add("Either your last pay stub or a copy of your tax return.");
		lst.add("As soon as we have the necessary information, credit cards will be available to you and your wife");
		lst.add("I appreciate your assistance");
		lst.add("BUYING ON CREDIT");
		lst.add("I'm going to buy furniture. ");
		lst.add("Can I buy it on credit?");
		lst.add("Of course, you can. ");
		lst.add("You can get a charge card from one of the large furniture stores. ");
		lst.add("This is a card for credit at one store. ");
		lst.add("Most large stores have their awn charge cards");
		lst.add("Where I should apply for this card?");
		lst.add("Apply directly to the store for this card");
		lst.add("What about major credit cards?");
		lst.add("You can use Visa, Master Card, or American Express. ");
		lst.add("These are cards from a bank or a credit company");
		lst.add("Where can I use these credit cards?");
		lst.add("You can use them at many different stores, restaurants, and hotels");
		lst.add("Where can I get an application for major credit cards?");
		lst.add("There are application forms for major credit cards at banks and at some hotels");
		lst.add("Would you tell me about various kinds of credit?");
		lst.add("There are two kinds of credit: monthly accounts and revolving accounts");
		lst.add("What's the difference between them?");
		lst.add("Monthly accounts must be paid in full every month. ");
		lst.add("You don't have to pay interest in this type of account. ");
		lst.add("In a revolving account, you pay a part of the total bill. ");
		lst.add("You also pay interest on the unpaid balance");
		lst.add("How much is the interest?");
		lst.add("The interest can be as high as 20%. ");
		lst.add("This means that you are paying much more than the cost of your purchase. ");
		lst.add("Credit cards can be useful, but they can also be expensive");
		lst.add("I think it depends on the card holder what kind of credit he prefers");
		lst.add("You are perfectly right. ");
		lst.add("I have several credit cards. ");
		lst.add("Since I don't want to pay any interest, I pay my bills in full");
		lst.add("Are American credit cards accepted overseas?");
		lst.add("Not all of them are acceptable there. ");
		lst.add("But if you use American Express, you won't have any trouble in stores, restaurants, and hotels the world over");
		lst.add("Thank you for the information.");
		lst.add("INQUIRING");
		lst.add("Hello, I would like to ask you for some information about your auto loan policy");
		lst.add("Are you our bank's customer?");
		lst.add("Yes, I'm. How much could I borrow?");
		lst.add("You can borrow up to 25000 dollars");
		lst.add("I need only 10000 dollars. Is there a down payment?");
		lst.add("No down payment is required");
		lst.add("What is the interest rate?");
		lst.add("If you keep over 20000 dollars in our bank, the interest rate is 10%");
		lst.add("I don't keep that much on my account");
		lst.add("If you go under 20000 dollars is 11.4%");
		lst.add("What about the term of an auto");
		lst.add("The bank lends the money for five years. I guess you are going to buy a new car?");
		lst.add("Yes, I am. But why are you asking  that question?");
		lst.add("If a customer applies for a loan for buying a used car, he has to pay a higher interest rate -13%. ");
		lst.add("Such a loan has to be paid up in 48 months");
		lst.add("I see. As I told you, I need 10000 dollars for buying a new car. ");
		lst.add("Could you please tell me what's the total I would have to pay up? ");
		lst.add("Just a moment. ");
		lst.add("If you borrow 10000 dollars, your total payment amounts to 13753 dollars. ");
		lst.add("Life insurance is included");
		lst.add("Is life insurance mandatory?");
		lst.add("Yes, it is");
		lst.add("And how much would my monthly payment be in case of a 10000 dollar loan?");
		lst.add("229 dollars");
		lst.add("Are my interest rate and monthly payment fixed for the full term of my loan?");
		lst.add("Yes, they are. So you don't have to worry about fluctuating interest rates");
		lst.add("One more question. ");
		lst.add("Can I pre-pay my loan at any time without penalty?");
		lst.add("Absolutely");
		lst.add("Thank you very much for this information. ");
		lst.add("Could I have a loan application for getting familiar with it?");
		lst.add("Of course");
		lst.add("Thanks");
		lst.add("AT THE GAS STATION");
		lst.add("What can I do for you?");
		lst.add("Fill it up, please");
		lst.add("I guess your car takes unleaded gas");
		lst.add("That's correct. ");
		lst.add("How much gas did it take?");
		lst.add("Eight gallons");
		lst.add("Would you check the oil, please. ");
		lst.add("It's below the full mark");
		lst.add("Please fill it up");
		lst.add("Will you wash the windshield for me?");
		lst.add("Okay. Should I check the tires too?");
		lst.add("Please, do. ");
		lst.add("How much do I owe you?");
		lst.add("11 dollars even");
		lst.add("One more thing. ");
		lst.add("What's the best way for me to get to interstate highway 87?");
		lst.add("No problem, sir. ");
		lst.add("Thank you. ");
		lst.add("Next week I'll come again for a tune-up. ");
		lst.add("I need a major one");
		lst.add("Our mechanic will be more than happy to help you. ");
		lst.add("If possible, try to make an appointment with our mechanic");
		lst.add("Of course, I'll try");
		lst.add("BUYING A CAR");
		lst.add("Good morning");
		lst.add("Good morning, sir. May I help you?");
		lst.add("I want to buy a new car");
		lst.add("Do you have anything special in mind?");
		lst.add("It shouldn't be either an expensive car or a big one");
		lst.add("I see. What about a Honda?");
		lst.add("It's a good and rather inexpensive car. ");
		lst.add("One of these cars is to the right of you");
		lst.add("How much is it?");
		lst.add("6900 dollars");
		lst.add("I've got a large family. ");
		lst.add("Therefore I'm looking for a mid-sized car");
		lst.add("If you are interested in a family car, the new Oldsmobile Delta 88 would be a good buy");
		lst.add("May I see it?");
		lst.add("It's right this way. ");
		lst.add("It's a very popular model. ");
		lst.add("Let's take a look. ");
		lst.add("Here we are. ");
		lst.add("This car will get you an excellent gas mileage. ");
		lst.add("Do you like the color?");
		lst.add("Yes, dark blue is my favorite color. ");
		lst.add("What special features does the car have?");
		lst.add("It has air conditioning, vinyl seat seat covers, and a radio");
		lst.add("Is it economical to run?");
		lst.add("Absolutely. ");
		lst.add("It uses lighter material in the body, and it has a new type of carburetor. ");
		lst.add("Therefor your gas consumption will be cut down. ");
		lst.add("Will you take a test drive to see how the car runs?");
		lst.add("Okay. ");
		lst.add("They get in, and the customer starts driving");
		lst.add("Several minutes later");
		lst.add("I like the car. ");
		lst.add("It's comfortable. ");
		lst.add("The steering and the brakes work well. ");
		lst.add("What about a trade-in?");
		lst.add("I can estimate your old car. ");
		lst.add("If you wish, I can ask my assistant to drive it around the block. ");
		lst.add("He could check out your car. He'll tell me what he thinks about a trade-in");
		lst.add("All right. There are the keys. ");
		lst.add("My car is only four years old. ");
		lst.add("I've not been in a single accident. ");
		lst.add("I've taken good care of the car");
		lst.add("Well, Let's go back to my office");
		lst.add("Let's see what kind of deal I can expect. ");
		lst.add("My decision depends on the price and the trade-in. ");
		lst.add("As soon as you can give me your ultimate price, I'll talk it over with my family. ");
		lst.add("I definitely need a new car");
		lst.add("INQUIRING ABOUT A CO-OP LOAN       ");
		lst.add("Hello. I'm your customer. ");
		lst.add("My name is Peter Vinogradov. ");
		lst.add("I'm come to ask you for some information of co-op loan policy");
		lst.add("How much would you like to borrow?");
		lst.add("120000 dollars");
		lst.add("Presently our bank offers adjustable interest rates for co-op. ");
		lst.add("Fixed rates are offered only to home buyers");
		lst.add("What is the difference between an adjustable rate and a fixed rate?");
		lst.add("An adjustable rate mortgage is a loan where the interest may be adjusted according to prevailing market rates. ");
		lst.add("If you apply for aco-op loan, your rate will be adjusted at the end of the year. ");
		lst.add("Until the end of the year, you are locked into a specific rate. ");
		lst.add("At the end of each year, the rate can be reassesed. ");
		lst.add("Do you follow me?");
		lst.add("Yes, I do. What about fixed rates?");
		lst.add("A fixed rate mortgage is a loan where the interest rate remains the same for the entire term of the mortgage, for instance, for 15 or 30 years. ");
		lst.add("What is the adjustable rate for a 120000 dollar co-op loan?");
		lst.add("7.625%+2.25 points");
		lst.add("Could you explain to me what a point is?");
		lst.add("A point is 1 percent of the amount you are borrowing");
		lst.add("How much would 2.25 points be in my particular case?");
		lst.add("2.25 points would equal 2700 dollars. ");
		lst.add("Once you are approved, you are locked into that rate");
		lst.add("Who approves my application?");
		lst.add("The bank's real estate department");
		lst.add("What information does the bank require for approving a co-op loan?");
		lst.add("Your employer will have to verify your income. ");
		lst.add("Besides you'll have to submit a credit report. ");
		lst.add("The bank will find out if there are any outstanding debts. ");
		lst.add("What proof of income is required if I am self-employed?");
		lst.add("A copy of your recent income tax return is required");
		lst.add("Thank you very much for your detailed information");
		lst.add("You are welcome");
		lst.add("TELEPHONE INFORMATION");
		lst.add("Good afternoon. ");
		lst.add("I was looking for a telephone number and couldn't find it in the directory");
		lst.add("Is it a business or a residence?");
		lst.add("A residence");
		lst.add("What's his or her full name?");
		lst.add("Sam Dolgin");
		lst.add("What's the correct spelling of his name?");
		lst.add("What's the borough?");
		lst.add("Brooklyn");
		lst.add("Do you know the street address?");
		lst.add("The address is: 1240 Ocean Parkway");
		lst.add("Ok. Phone number is 763 5533");
		lst.add("Directory Assistance. Can I help you?");
		lst.add("Can I dial direct to Munich, West Germany?");
		lst.add("Yes. First you dial the international code number - 011");
		lst.add("What's to be done next?");
		lst.add("Next you dial the country code. ");
		lst.add("For West Germany that's 49. ");
		lst.add("The city code for Munich is 89. ");
		lst.add("Then you dial the local telephone number");
		lst.add("Thank you");
		lst.add("May I help you?");
		lst.add("I would like to bill my call to a third number. ");
		lst.add("The number is: 212-371-1839");
		lst.add("Who is calling, please?");
		lst.add("Alexander is calling. ");
		lst.add("Somebody should be at home. ");
		lst.add("TOLL-FREE TELEPHONE CALLS");
		lst.add("Hi, Jack. It's nice to see you. How are you?");
		lst.add("I'm fine. I, m glad to see you");
		lst.add("Do you have a couple of spare minutes?");
		lst.add("Of course, I do");
		lst.add("Calling Social Security Administration");
		lst.add("You have reached the Social Security Administration. ");
		lst.add("All our representatives are busy. ");
		lst.add("Please hold, and the next available representative will be with you, as soon as possible. ");
		lst.add("This is Robert Miller. May I help you?");
		lst.add("An hour ago, my wallet was stolen. ");
		lst.add("My social security card was in it. ");
		lst.add("I'd like to order a new card.");
		lst.add("What's your card number?");
		lst.add("The number is........ ");
		lst.add("Your name and address?");
		lst.add("Simon Chernyak. -100 Montgomery Street, Apartment 2-E. Jersey City, New Jersey 07300");
		lst.add("May I have your telephone number?");
		lst.add("201-637-2237");
		lst.add("We'll send you a new card. You'll get it in a week's time");
		lst.add("Thank you");
		lst.add("Calling AT & T National Service Center");
		lst.add("Good evening. ");
		lst.add("This is Mary Boyd. ");
		lst.add("May I help you?");
		lst.add("Good evening. ");
		lst.add("Today I bought an electronic typewriter at one of your stores. ");
		lst.add("I've a question");
		lst.add("I'll be glad to answer it");
		lst.add("I attempted to set the page margins, but the typewriter started beeping. ");
		lst.add("Evidently something was wrong");
		lst.add("Page margins cannot be set closer than one inch. ");
		lst.add("The typewriter will beep if you attempt to do so, or if you press the wrong margin key");
		lst.add("Thank you for your explanation");
		lst.add("THE WEATHER");
		lst.add("What's the weather today?");
		lst.add("The temperature has fallen again");
		lst.add("I enjoy the cold weather");
		lst.add("Don't you mind the cold?");
		lst.add("Not at all. ");
		lst.add("I prefer a cold winter to a hot, muggy summer");
		lst.add("I agree. ");
		lst.add("After the terrible August we had last year, low temperatures are kind of refreshing");
		lst.add("In August there wasn't a breeze anywhere. ");
		lst.add("There was ninety percent humidity, and the temperature stayed above ninety degrees for 15 straight days");
		lst.add("It's six o'clock now. ");
		lst.add("I'll turn on the radio. ");
		lst.add("Let's listen to the weather report");
		lst.add("As the cold front crosses the region tonight, temperatures will drop considerably. ");
		lst.add("The present temperature is 26 degrees. ");
		lst.add("Tonight will be partly cloudy. ");
		lst.add("Tomorrow will become sunny, windy, and very cold. ");
		lst.add("High 20, low 16. ");
		lst.add("Strong winds from the north will bring Arctic air to the region. ");
		lst.add("Snow will develop at the end of the week");
		lst.add("Did you listen to the weather forecast?");
		lst.add("Yes, I did. ");
		lst.add("The mild weather will continue. ");
		lst.add("Scattered showers will occur tomorrow night");
		lst.add("And what about the day after tomorrow?");
		lst.add("Skies will begin to clear. ");
		lst.add("Drier, colder air will arrive from the north-west. ");
		lst.add("Sunny but cold weather will prevail the day after tomorrow");
		lst.add("At this time of the year, the weather is so changeable");
		lst.add("It's a beautiful day");
		lst.add("Yes. It's a fine day. The sun is shining");
		lst.add("It looks as if we are going to have a couple of fine days");
		lst.add("It's unusual weather for March");
		lst.add("I hope that's the beginning of spring");
		lst.add("I'm afraid the weather changes rather often. ");
		lst.add("A sudden snowfall is quite possible. ");
		lst.add("REPAIRING THINGS");
		lst.add("I would like to have these shoes repaired. ");
		lst.add("As you see, my heels are worn down");
		lst.add("Yes, new heels are to be put on");
		lst.add("Will you repair the shoes while I wait?");
		lst.add("I'm very busy now. ");
		lst.add("You can pick up your shoes tomorrow");
		lst.add("At what time?");
		lst.add("Any time");
		lst.add("How much will it cost?");
		lst.add("Six dollars. What's your name, please?");
		lst.add("Vladimir Soloveychik");
		lst.add("All right. ");
		lst.add("Here's your slip. ");
		lst.add("You'll pay tomorrow when getting the shoes");
		lst.add("Thank you");
		lst.add("Do you do alterations?");
		lst.add("Yes, we do");
		lst.add("I'd like to have these pants shortened");
		lst.add("All right. How many inches?");
		lst.add("Not more than two");
		lst.add("Would you try the pants on? ");
		lst.add("I'd like to see them on you. Our fitting room is to the left");
		lst.add("Okay. Just a minute");
		lst.add("Two inches will be fine");
		lst.add("When can I pick up the pants?");
		lst.add("They will be ready on Monday");
		lst.add("Excuse me, is there a camera shop anywhere in this neighborhood?");
		lst.add("Turn right at the next corner. ");
		lst.add("There is a camera shop. ");
		lst.add("You can't miss it");
		lst.add("Thanks. ");
		lst.add("He is entering the camera shop");
		lst.add("Good morning");
		lst.add("Good morning. May I help you?");
		lst.add("Yes, I'd like to have this film developed and printed.");
		lst.add("Okay. Anything else?");
		lst.add("Please give me two films for this camera");
		lst.add("Here you are. Four dollars and 35 cents");
		lst.add("When will my pictures be ready?");
		lst.add("It will take five days. Here's your receipt");
		lst.add("Do you repair shavers?");
		lst.add("Yes, I do");
		lst.add("Okay. I've my shaver with me. Can you fix it?");
		lst.add("When did you buy it?");
		lst.add("About five months ago");
		lst.add("Did you keep the guarantee?");
		lst.add("No, I didn't. I lost it");
		lst.add("Then I'll have to charge you");
		lst.add("How much will it cost?");
		lst.add("That depends on what's wrong with it");
		lst.add("I think the batteries are dead. ");
		lst.add("They should be replaced");
		lst.add("I've to check it. ");
		lst.add("Could you come in tomorrow?");
		lst.add("All right");
		lst.add("AT THE DRUGSTORE");
		lst.add("Could you fill this prescription?");
		lst.add("Just a minute. ");
		lst.add("I've to check if we have this in stock. ");
		lst.add("Sorry. Today you can get only 37 capsules. ");
		lst.add("Is that okay with you?");
		lst.add("All right. When will you have the rest");
		lst.add("We owe you 23 capsules.");
		lst.add("Can you drop in the day after tomorrow?");
		lst.add("Of course. ");
		lst.add("I'll come the day after tomorrow if I can get the other capsules");
		lst.add("That's for sure");
		lst.add("Should I pay now or later?");
		lst.add("Now will be fine. ");
		lst.add("Have a seat, please. ");
		lst.add("Your medication will be ready in five minutes. ");
		lst.add("I'll give you a receipt. ");
		lst.add("I'll indicate there that we owe you 23 capsules");
		lst.add("Can I help you?");
		lst.add("Could you give me something for a toothache?");
		lst.add("I would recommend you Tylenol. ");
		lst.add("It's for temporary relief of minor pain");
		lst.add("Don't you have a painkiller?");
		lst.add("We've plenty of them. ");
		lst.add("But without a doctor's prescription you can't have it");
		lst.add("Okay. What's to be done?");
		lst.add("Please give me Tylenol, extra-strength-50 capsules. ");
		lst.add("I've to see my dentist anyway");
		lst.add("Good evening. What can I do for you?");
		lst.add("I've a long list of things I need. ");
		lst.add("Most items I can find on your shelves without any help. ");
		lst.add("Please tell me only where I should look for vitamins and adhesive tapes");
		lst.add("Aisle3-for vitamins, Aisle2-for adhesive tapes. ");
		lst.add("Anything else? ");
		lst.add("Aspirin, a deodorant, shaving cream, and shampoo for my wife.");
		lst.add("You'll find aspirin in aisle 1. ");
		lst.add("Aspirin comes in bottles of fifty, one hundred, and two hundred tablets. In aisle 4, you can find deodorants, shampoos, and shaving creams. ");
		lst.add("As to the shampoo, we have a special on a new brand");
		lst.add("Is it for oily hair?");
		lst.add("Yes, it is");
		lst.add("That's the right thing for my wife. Thank you. Now I can find the items I need without any difficulties");
		lst.add("USEFUL WORDS AND EXPRESSIONS");
		lst.add("Ointment");
		lst.add("Drops");
		lst.add("Iodine");
		lst.add("Liquid");
		lst.add("Lotion");
		lst.add("Powder");
		lst.add("Soap");
		lst.add("Scented soap");
		lst.add("Scissors");
		lst.add("Comb");
		lst.add("Hairbrush");
		lst.add("Toothpaste");
		lst.add("Toothbrush");
		lst.add("Paper towels");
		lst.add("Nail tile");
		lst.add("Nail polish");
		lst.add("Polish remover");
		lst.add("(Razor)blade");
		lst.add("Disposable blades");
		lst.add("sponge");
		lst.add("pantyhose       ");
		lst.add("shower cap       ");
		lst.add("laxative       ");
		lst.add("AT THE DENTIST'S OFFICE");
		lst.add("Good morning, can I help you?");
		lst.add("Yes, my name is Anne Pearl. ");
		lst.add("I have an appointment for ten o'clock");
		lst.add("Have a seat, please. ");
		lst.add("The doctor will see you soon");
		lst.add("Thank you");
		lst.add("Dr. Smith, this is Ms. Pearl");
		lst.add("Hello, Ms. Pearl. ");
		lst.add("Please come with me. ");
		lst.add("Sit down. ");
		lst.add("What's the problem?");
		lst.add("I have a toothache on the left upper side");
		lst.add("How long have you had it?");
		lst.add("For about three days. ");
		lst.add("I have a filling that is loose. ");
		lst.add("I'm afraid it is about to drop out");
		lst.add("Let me take a look at it. ");
		lst.add("Open your mouth wide, please. ");
		lst.add("I'll take an X-ray");
		lst.add("Good");
		lst.add("There's a rather deep cavity on the right side of the tooth");
		lst.add("Will you have to pull the tooth?");
		lst.add("No. I hope to save your tooth. ");
		lst.add("I'll give you an injection of Novocaine");
		lst.add("Okay");
		lst.add("Now I can drill the tooth. ");
		lst.add("You don't feel any pain, do you?");
		lst.add("No, I don't");
		lst.add("I'd suggest that -besides the usual filling-we put a crown on your tooth. ");
		lst.add("That can save it. ");
		lst.add("I'll put a temporary crown there today. ");
		lst.add("The permanent crown will be ready in about 10 days. ");
		lst.add("Then you'll come back. ");
		lst.add("Is it all right with you? ");
		lst.add("If you think it's the only way to save the tooth, then go ahead. ");
		lst.add("I realize a crown is rather expensive. ");
		lst.add("But what's to be done?");
		lst.add("Okay. You can eat in two hours. Call my secretary for an appointment next week");
		lst.add("Thank you, doctor");
		lst.add("AT THE DOCTOR'S OFFICE");
		lst.add("Good morning. Can I help you?");
		lst.add("Good morning. My name is Rozov. ");
		lst.add("I have an 11 o'clock appointment");
		lst.add("Please, take a seat. ");
		lst.add("The doctor will see you soon");
		lst.add("Thank you");
		lst.add("Hello, Mr. Rozov. ");
		lst.add("Come in, please. ");
		lst.add("Sorry to have kept you waiting");
		lst.add("That's all right. ");
		lst.add("Did you get all the test results?");
		lst.add("Yes, I got them last hight. ");
		lst.add("As to the tests, everything is okay. ");
		lst.add("Your cardiogram is normal too");
		lst.add("But what about the X-ray?");
		lst.add("Is anything wrong?");
		lst.add("The X-ray shows emphysema. ");
		lst.add("That's evidently the result of your heavy smoking. ");
		lst.add("Your breath shortness and your cough are probably caused by the emphysema");
		lst.add("Is that serious?");
		lst.add("It could become extremely serious. ");
		lst.add("If you are worried about your health cut out your smoking");
		lst.add("Certainly, I'll try to stop smoking. ");
		lst.add("What else could you advise me to do for improving my health?");
		lst.add("You should do daily exercises. ");
		lst.add("Eat small meals four or five times a day");
		lst.add("Do I have to go to the hospital?");
		lst.add("No. I'll give you a prescription. ");
		lst.add("Take the pills three times a day. ");
		lst.add("I want you to see me again in three weeks. ");
		lst.add("Stay well");
		lst.add("Thank you, doctor");
		lst.add("What 's troubling you?");
		lst.add("I've caught a cold. ");
		lst.add("I have a sore throat and a bad cough");
		lst.add("Put this thermometer under your tongue.");
		lst.add(" I want to see if you have a fever. ");
		lst.add("Let me see... ");
		lst.add("Yes, you have a temperature. ");
		lst.add("When did you first feel ill?");
		lst.add("A couple of days ago");
		lst.add("Let me examine you. ");
		lst.add("Take a deep breath. ");
		lst.add("Now I want to test your blood pressure. ");
		lst.add("Your blood pressure is slightly above normal, but nothing to worry about. ");
		lst.add("Any other trouble?");
		lst.add("Doctor, I haven't been sleeping well");
		lst.add("I'll give you some sleeping pills. ");
		lst.add("Take the tablets as prescribed-you take only one at bedtime. ");
		lst.add("You must stay in bed for several days until your temperature has gone down. ");
		lst.add("Here's a prescription for your flu. ");
		lst.add("Come in again to see me in ten days");
		lst.add("Okay. Thank you, doctor");
		lst.add("USEFUL WORDS AND EXPRESSIONS");
		lst.add("Headache(s)");
		lst.add("Dizziness");
		lst.add("Ulcer");
		lst.add("Liver disease");
		lst.add("Kidney disease");
		lst.add("Stomach disease");
		lst.add("Insomnia");
		lst.add("Pneumonia");
		lst.add("Heart attack");
		lst.add("Heart disease");
		lst.add("Stroke");
		lst.add("Malignant tumor");
		lst.add("Cancer");
		lst.add("Benign tumor");
		lst.add("Hypertension");
		lst.add("Hypotension");
		lst.add("Bleeding");
		lst.add("Pus");
		lst.add("Inflammation");
		lst.add("Cold");
		lst.add("Runny nose");
		lst.add("Hoarse voice");
		lst.add("Sore throat");
		lst.add("Constipation");
		lst.add("Diarrhea");
		lst.add("Upset stomach");
		lst.add("Heartburn");
		lst.add("Cramp");
		lst.add("To gain weight");
		lst.add("To lose weight");
		lst.add("DOCTORS ON CALL");
		lst.add("Hello. May I help you?");
		lst.add("Is this the number for making arrangements for doctor house calls?");
		lst.add("Yes, it is. Doctors make house calls 24 hours a day, seven days a week in all five borough of New York");
		lst.add("When can I request a house call?");
		lst.add("Whenever your family doctor does not have office hours, for instance, at night, or you are too sick to leave your home. ");
		lst.add("In emergency cases, call 911");
		lst.add("How does your service work?");
		lst.add("That's quite simple. ");
		lst.add("Specially trained operators take your full name, address, phone number and a brief explanation of your problem. ");
		lst.add("They then schedule you with a doctor already on house calls nearby");
		lst.add("When can I expect the doctor to arrive?");
		lst.add("In most cases, expect the doctor within two hours");
		lst.add("What kind of medical services are available in my home?");
		lst.add("Our doctors perform examinations, prescribe medicine, give injections and recommend other required services");
		lst.add("Are such services as blood tests, electrocardiograms and X-rays available in my home?");
		lst.add("Absolutely. ");
		lst.add("If required, the doctor can perform these services");
		lst.add("When am I supposed to pay the doctor?");
		lst.add("At the end of the doctor's visit");
		lst.add("Will the visiting doctor fill out any insurance forms required?");
		lst.add("Of course, he will. ");
		lst.add("Many insurance plans pay for doctor's calls. ");
		lst.add("Often we are permitted to bill insurance companies directly");
		lst.add("Is Medicare accepted by Doctors on Call?");
		lst.add("You pay the doctor. ");
		lst.add("He fills out the Medicare form");
		lst.add("Can you tell me more about the doctor's charge?");
		lst.add("When you call for an appointment, ask our operator about our charges. ");
		lst.add("They are quite reasonable, comparable to an office visit");
		lst.add("Thank you for the information");
		lst.add("DISCUSSING NUTRITION PROBLEMS");
		lst.add("I've been living in this country for more than seven years, but I don't yet understand why there is so much talk about nutrition as a growing sciense. ");
		lst.add("Americans want to be healthy. ");
		lst.add("But most of us have no understanding of nutrition problems");
		lst.add("Whenever I see my family doctor, he advises me to stick to a low cholesterol diet");
		lst.add("And do you follow his advice?");
		lst.add("It's hard to stick to a diet with my busy schedule");
		lst.add("For your health, it is very important to get a balanced diet");
		lst.add("Can people who don't eat meat or fish stay healthy?");
		lst.add("Absolutely. By eating enough dairy foods and meat alternates, people can get essential proteins");
		lst.add("What about the nutritional value of canned vegetables that we buy at the supermarket?");
		lst.add("The nutritional difference depends more on how vegetables are prepared than on whether they are bought fresh or canned");
		lst.add("I wonder how knowledgeable you are. ");
		lst.add("You could become a professional dietitian");
		lst.add("It's just my hobby to read about food and health");
		lst.add("I was told to avoid such foods as bread or potatoes. ");
		lst.add("What's your view?");
		lst.add("By avoiding bread and potatoes you cut out several B vitamins, vitamin C and other nutrients");
		lst.add("Are extra vitamin dosages useful?");
		lst.add("You shouldn't take more vitamins than the body needs");
		lst.add("Thank you for your valuable information");
		lst.add("AIRPLANES RESERVATIONS");
		lst.add("Can I help you?");
		lst.add("I want to fly to London next week. ");
		lst.add("I'd like to make reservations for a round ticket");
		lst.add("What day are you planning to leave for London?");
		lst.add("On the 12th of March");
		lst.add("There are three flights to London on that day - at 10 AM, at 8 and 9 PM");
		lst.add("Do you have any preference about the time of the day?");
		lst.add("I'd rather leave at 9 PM. ");
		lst.add("I want to get to London early in the morning");
		lst.add("I can make a reservation for a TWA flight. ");
		lst.add("Are you going to travel first class or economy?");
		lst.add("I prefer economy. ");
		lst.add("How much will it be?");
		lst.add("440 dollars");
		lst.add("Are the meals and refreshments served on the flight?");
		lst.add("Yes, they are");
		lst.add("What's the flight time?");
		lst.add("Six hours");
		lst.add("What's the London airport we'll arrive at?");
		lst.add("Heathrow Airport. ");
		lst.add("How many days are you planning to stay in London?");
		lst.add("Seven days");
		lst.add("When would you like to fly home from London?");
		lst.add("March 22nd");
		lst.add("All right. Your name and address?");
		lst.add("Boris Boguslavski. 64-92 99th Street. Rego-Park, New York 11374");
		lst.add("And your telephone number?");
		lst.add("439-7286");
		lst.add("Will you pay by credit card?");
		lst.add("Yes, by Master Card. Number... ");
		lst.add("Valid until January 15, 2022. ");
		lst.add("When can I get my tickets?");
		lst.add("You'll have them two days before your departure.");
		lst.add("BOOKING TRAIN TICKETS");
		lst.add("May I help you?");
		lst.add("I'd like to book two roundtrip tickets to Boston");
		lst.add("Okay. When are you leaving?");
		lst.add("Next Sunday");
		lst.add("What time do you prefer?");
		lst.add("As far as I know, there is a train that leaves for Boston at 9 AM. ");
		lst.add("I'd like to go by that train");
		lst.add("Do you prefer a smoking car or a car for non-smokers?");
		lst.add("A non-smoking car, please");
		lst.add("I'll reserve for you two tickets for the nine o'clock Sunday train");
		lst.add("Roundtrip tickets?");
		lst.add("Yes");
		lst.add("How much is it?");
		lst.add("168 dollars");
		lst.add("When does the train arrive in Boston?");
		lst.add("At 11 45 AM. ");
		lst.add("Your name, please?");
		lst.add("Anatoli Petrovski. ");
		lst.add("Where can I get the tickets?");
		lst.add("At the railroad station, window No. 9");
		lst.add("HOTEL RESERVATIONS");
		lst.add("Embassy Hotel. Good morning. ");
		lst.add("My name is Doris Morgan. Can I help you?");
		lst.add("Good morning. ");
		lst.add("I'm calling from New York. ");
		lst.add("I'd like to have a reservation for next Monday. ");
		lst.add("My name is Anatoli Petrovski");
		lst.add("We have several hotels in Chicago. ");
		lst.add("Which area are you interested in?");
		lst.add("I prefer downtown");
		lst.add("All right. Do you want a single or a double room?");
		lst.add("A single room, please");
		lst.add("Okay, Mr. Petrovski");
		lst.add("Is it a front room or back room?");
		lst.add("It's a front room. ");
		lst.add("But our hotel is located on a quite street");
		lst.add("What's the price of this room per night?");
		lst.add("Seventy dollars a night. ");
		lst.add("How long do you expect to stay?");
		lst.add("I'll be staying for a week. ");
		lst.add("Will the room be reserved for me? Okay?");
		lst.add("You are all set. ");
		lst.add("Could I have your telephone number?");
		lst.add("431-2211. I'll pay by credit card");
		lst.add("See you next week, Mr. Petrovski");
		lst.add("Thank you for calling us");
		lst.add("CONCERT TICKET RESERVATIONS");
		lst.add("May I help you?");
		lst.add("I'd like to order two cert on Friday, December 23rd.");
		lst.add("There are only orchestra and several balcony seats left");
		lst.add("What about the balcony seats? ");
		lst.add("Can one see and hear well from there?");
		lst.add("These are rather good seats. ");
		lst.add("Just inn the center of the third row. ");
		lst.add("Could I have a reservation for two seats on the balcony?");
		lst.add("Yes, of course. Your credit card? ");
		lst.add("Visa");
		lst.add("The information I need is: your first and last name, the number of your credit card, its expiration date, and your telephone number");
		lst.add("My name is Peter Grigoryev.   ");
		lst.add("The Visa card number is.......... It's valid until October 1, 1990.");
		lst.add("My telephone number is: 379-2243. ");
		lst.add("How much are the tickets?");
		lst.add("The price of these tickets is 15 dollars. ");
		lst.add("For ordering them by telephone there is a surcharge of 3 dollars per ticket. ");
		lst.add("You'll be charged 36 dollars");
		lst.add("Okay. Where and when can I get the tickets?");
		lst.add("You'll get the tickets at the box to pick them up at seven thirty");
		lst.add("AT A HOTEL");
		lst.add("Good afternoon. I'd like to check in");
		lst.add("Do you have a reservation with us?");
		lst.add("Yes, I do. I made a reservation by phone last night");
		lst.add("Your name, please?");
		lst.add("Gregory Borisov from San Francisco");
		lst.add("Would you spell your last name, please?");
		lst.add("'''B'' as in ''Billy'', ''O'' as in ''Oscar'', ''R'' as in ''Robert'', ''I'' as in ''Irene'', ''S'' as in ''Sam'', ''O'' as in ''Oscar'', ''V'' as in ''Victor''. '");
		lst.add("Okay. let me see. ");
		lst.add("You have a reservation for a single room. Is that correct? ");
		lst.add("Perfectly correct");
		lst.add("Have you already decided how many nights to stay?");
		lst.add("At least until Wednesday. ");
		lst.add("But I may stay longer than that. ");
		lst.add("When should I inform you about it?");
		lst.add("Let us know about your decision Tuesday night. ");
		lst.add("You can give us a ring until 11 PM");
		lst.add("All right. What 's the price of the");
		lst.add("75 dollars per night. ");
		lst.add("Please fill out the registration card. ");
		lst.add("Print your name and home address");
		lst.add("Should I sign my name?");
		lst.add("Put you signature right here.");
		lst.add("Okay. Will you pay cash or by credit card?");
		lst.add("By credit card. ");
		lst.add("Do you need it right now?");
		lst.add("You can give me your credit card before checking out");
		lst.add("By the way, what's the checkout time?");
		lst.add("One o'clock in the afternoon");
		lst.add("Thank you. I have some additional questions");
		lst.add("I'll be glad to answer them");
		lst.add("What about room service?");
		lst.add("Room service is available from 6 AM to 10 PM. ");
		lst.add("You can dial your order from the telephone in your room");
		lst.add("Where is your restaurant?");
		lst.add("The restaurant is on the 25 th floor. ");
		lst.add("We also have a coffee shop. ");
		lst.add("It 's right here in the lobby");
		lst.add("Thank you for the information");
		lst.add("You are welcome. ");
		lst.add("A bellboy will help you with your luggage. ");
		lst.add("Your room is 1215. ");
		lst.add("Enjoy your stay");
		lst.add("Thanks");
		lst.add("AT A RESTAURANT");
		lst.add("Good evening. Two for dinner?");
		lst.add("Yes, that's right");
		lst.add("Where would you like to sit?");
		lst.add("Could we have a table near the window, please?");
		lst.add("Come with me, please");
		lst.add("Could we have the menu?");
		lst.add("Certainly");
		lst.add("waiter brings the menu");
		lst.add("We have to make up our mind. ");
		lst.add("We'll order in a few minutes");
		lst.add("Do you want an appetizer, Vera? ");
		lst.add("Oysters, lox, smoked herring, or avocado?");
		lst.add("Does it come with the dinner?");
		lst.add("No, it's a la carte");
		lst.add("Let's see.... the dinner includes salad, an entree, vegetables and potatoes as side dishes, a dessert, and coffee. ");
		lst.add("That's more than enough");
		lst.add("Okay. We'll order a dinner without an appetizer. ");
		lst.add("What about the entree? ");
		lst.add("What would you like-veal, roast, beef, steak, or chicken?");
		lst.add("We've had chicken at home rather often.");
		lst.add(" When we eat out, I'd like to get something we don't have at home. ");
		lst.add("As for me, I'd like to have a steak");
		lst.add("So would I");
		lst.add("Are you ready to order now?");
		lst.add("Yes. Can we begin with the salad?");
		lst.add("Certainly, sir. ");
		lst.add("What kind of dressing would you like?");
		lst.add("Just olive oil and vinegar for both of us");
		lst.add("And for your entree?");
		lst.add("Two steaks, please");
		lst.add("Rare, medium, or well done?");
		lst.add("Medium, please");
		lst.add("Is there a choice of vegetables and potatoes?");
		lst.add("No, madam. We serve a daily special. ");
		lst.add("Today you can have mashed potatoes. ");
		lst.add("The vegetable of this day is asparagus");
		lst.add("It's all right with me. What about you, Vera?");
		lst.add("It's okay");
		lst.add("Would you like to see the menu?");
		lst.add("We'd like a carafe of Chablis");
		lst.add("Fine. Will you order your dessert now? ");
		lst.add("Can we order it later?");
		lst.add("Of course");
		lst.add("AT THE LIBRARY");
		lst.add("I'd like to get a library card");
		lst.add("Do you live in this neighborhood?");
		lst.add("Yes, I do. I live at 120 Maiden Lane");
		lst.add("May I see your driver's license?");
		lst.add("Sorry, I don't have it with me");
		lst.add("Do you have any other proof of address?");
		lst.add("Yes, I do. Here's a letter I received from my bank a week ago. ");
		lst.add("On the back side you can see my address");
		lst.add("That's okay. Here's an application card. ");
		lst.add("Fill in the front application. ");
		lst.add("Please sing your full name");
		lst.add("Could you help me?");
		lst.add("I'd be glad to. What is it?");
		lst.add("I can't find some of the books that are listed in the catalog");
		lst.add("Did you write down the numbers of the books you can't find?");
		lst.add("Yes, i did. Here they are");
		lst.add("Was the letter 'R' in the right corner of the catalog card?");
		lst.add("Yes, it was");
		lst.add("Evidently you are looking for reference books. 'R' means Reference Room");
		lst.add("I need some dictionaries");
		lst.add("You'll find them in the Reference entrance");
		lst.add("What about magazines and newspapers?");
		lst.add("You've to look for them in the Periodical Room.");
		lst.add("Ask there for a separate catalog for periodicals. ");
		lst.add("Half a year ago, a book on Russian literature was published in England. ");
		lst.add("I checked your catalog and couldn't find it.");
		lst.add("Do you know the name of the author the title, and the publishing house?");
		lst.add("Yes, I do");
		lst.add("Then you can make out this post have card. ");
		lst.add("Should a branch of our library the book you are interested in, we'll order it for you and let you know about it. ");
		lst.add("That'll be twenty cents for the card, please");
		lst.add("I wonder if you could give me some information");
		lst.add("I'd be happy to. What can I do for you?");
		lst.add("I want to find a recently published history of philosophy. ");
		lst.add("Where should I look for it?");
		lst.add("These shelves to your right have our latest acquisitions in various fields. ");
		lst.add("In the philosophy section, you'll certainly find the book you are looking for. ");
		lst.add("The books are in alphabetical order according to the author's last name.");
		lst.add("Thank you. ");
		lst.add("How many books may I take out at one time?");
		lst.add("You can borrow three books at one time");
		lst.add("What about the magazines?");
		lst.add("Some of them are not to be lent. ");
		lst.add("You've read them at the library. ");
		lst.add("Other magazines can be taken out, but not than two at one time");
		return lst;
	}
}