class EngExpressions {
	String word;
	EngExpressions();
	static getList(){
		List<String> lst = [];
		lst.add("Be careful.");
		lst.add("Be careful driving.");
		lst.add("Can you translate this for me?");
		lst.add("Chicago is very different from Boston.");
		lst.add("Don't worry.");
		lst.add("Everyone knows it.");
		lst.add("Everything is ready.");
		lst.add("Excellent.");
		lst.add("From time to time.");
		lst.add("Good idea.");
		lst.add("He likes it very much.");
		lst.add("Help!");
		lst.add("He's coming soon.");
		lst.add("He's right.");
		lst.add("He's very annoying.");
		lst.add("He's very famous.");
		lst.add("How are you?");
		lst.add("How's work going?");
		lst.add("Hurry!");
		lst.add("I ate already.");
		lst.add("I can't hear you.");
		lst.add("I'd like to go for a walk.");
		lst.add("I don't know how to use it.");
		lst.add("I don't like him.");
		lst.add("I don't like it.");
		lst.add("I don't speak very well.");
		lst.add("I don't understand.");
		lst.add("I don't want it.");
		lst.add("I don't want that.");
		lst.add("I don't want to bother you.");
		lst.add("I feel good.");
		lst.add("If you need my help, please let me know.");
		lst.add("I get off of work at 6.");
		lst.add("I have a headache.");
		lst.add("I hope you and your wife have a nice trip.");
		lst.add("I know.");
		lst.add("I like her.");
		lst.add("I'll call you when I leave.");
		lst.add("I'll come back later.");
		lst.add("I'll pay.");
		lst.add("I'll take it.");
		lst.add("I'll take you to the bus stop.");
		lst.add("I lost my watch.");
		lst.add("I love you.");
		lst.add("I'm an American.");
		lst.add("I'm cleaning my room.");
		lst.add("I'm cold.");
		lst.add("I'm coming to pick you up.");
		lst.add("I'm going to leave.");
		lst.add("I'm good, and you?");
		lst.add("I'm happy.");
		lst.add("I'm hungry.");
		lst.add("I'm married.");
		lst.add("I'm not busy.");
		lst.add("I'm not married.");
		lst.add("I'm not ready yet.");
		lst.add("I'm not sure.");
		lst.add("I'm sorry, we're sold out.");
		lst.add("I'm thirsty.");
		lst.add("I'm very busy. I don't have time now.");
		lst.add("I need to change clothes.");
		lst.add("I need to go home.");
		lst.add("I only want a snack.");
		lst.add("Is Mr. Smith an American?");
		lst.add("Is that enough?");
		lst.add("I think it's very good.");
		lst.add("I think it tastes good.");
		lst.add("I thought the clothes were cheaper.");
		lst.add("It's longer than 2 miles.");
		lst.add("I've been here for two days.");
		lst.add("I've heard Texas is a beautiful place.");
		lst.add("I've never seen that before.");
		lst.add("I was about to leave the restaurant when my friends arrived.");
		lst.add("Just a little.");
		lst.add("Just a moment.");
		lst.add("Let me check.");
		lst.add("Let me think about it.");
		lst.add("Let's go have a look.");
		lst.add("Let's practice English.");
		lst.add("May I speak to Mrs. Smith please?");
		lst.add("More than that.");
		lst.add("Never mind.");
		lst.add("Next time.");
		lst.add("No.");
		lst.add("Nonsense.");
		lst.add("No, thank you.");
		lst.add("Nothing else.");
		lst.add("Not recently.");
		lst.add("Not yet.");
		lst.add("Of course.");
		lst.add("Okay.");
		lst.add("Please fill out this form.");
		lst.add("Please take me to this address.");
		lst.add("Please write it down.");
		lst.add("Really?");
		lst.add("Right here.");
		lst.add("Right there.");
		lst.add("See you later.");
		lst.add("See you tomorrow.");
		lst.add("See you tonight.");
		lst.add("She's pretty.");
		lst.add("Sorry to bother you.");
		lst.add("Stop!");
		lst.add("Take a chance.");
		lst.add("Take it outside.");
		lst.add("Tell me.");
		lst.add("Thanks for everything.");
		lst.add("Thanks for your help.");
		lst.add("Thank you.");
		lst.add("Thank you miss.");
		lst.add("Thank you sir.");
		lst.add("Thank you very much.");
		lst.add("That looks great.");
		lst.add("That's alright.");
		lst.add("That's enough.");
		lst.add("That's fine.");
		lst.add("That's it.");
		lst.add("That smells bad.");
		lst.add("That's not fair.");
		lst.add("That's not right.");
		lst.add("That's right.");
		lst.add("That's too bad.");
		lst.add("That's too many.");
		lst.add("That's too much.");
		lst.add("The book is under the table.");
		lst.add("They'll be right back.");
		lst.add("They're the same.");
		lst.add("They're very busy.");
		lst.add("This doesn't work.");
		lst.add("This is very difficult.");
		lst.add("This is very important.");
		lst.add("Try it.");
		lst.add("Very good, thanks.");
		lst.add("We like it very much.");
		lst.add("Would you take a message please?");
		lst.add("Yes, really.");
		lst.add("You're beautiful.");
		lst.add("You're very nice.");
		lst.add("You're very smart.");
		lst.add("Your things are all here.");
		lst.add("Certainly!");
		lst.add("Good afternoon.");
		lst.add("Good evening sir.");
		lst.add("Good Luck.");
		lst.add("Good morning.");
		lst.add("Great.");
		lst.add("Happy Birthday.");
		lst.add("Have a good trip.");
		lst.add("Hello.");
		lst.add("Nice to meet you");
		lst.add("Please call me.");
		lst.add("About 300 kilometers.");
		lst.add("A one way ticket.");
		lst.add("Are you going to help her?");
		lst.add("A round trip ticket.");
		lst.add("At what time?");
		lst.add("Can I make an appointment for next Wednesday?");
		lst.add("Can you repeat that please?");
		lst.add("Does this road go to New York?");
		lst.add("Do you have enough money?");
		lst.add("Do you know how to cook?");
		lst.add("Do you know what this says?");
		lst.add("Do you want me to come and pick you up?");
		lst.add("Follow me.");
		lst.add("From here to there.");
		lst.add("Go straight ahead.");
		lst.add("Have you arrived?");
		lst.add("Have you been to Boston?");
		lst.add("How do I get there?");
		lst.add("How do I get to Daniel Street?");
		lst.add("How do I get to the American Embassy?");
		lst.add("How long does it take by car?");
		lst.add("How long does it take to get to Georgia?");
		lst.add("How long is the flight?");
		lst.add("How was the movie?");
		lst.add("I'd like to make a phone call.");
		lst.add("I'd like to make a reservation.");
		lst.add("I have a question I want to ask you./ I want to ask you a question.");
		lst.add("I'll take that one also.");
		lst.add("I'm coming right now.");
		lst.add("I'm going home in four days.");
		lst.add("I'm leaving Tomorrow.");
		lst.add("I'm looking for the post office.");
		lst.add("Is this pen yours?");
		lst.add("I wish I had one.");
		lst.add("One ticket to New York please.");
		lst.add("One way or round trip?");
		lst.add("Please speak slower.");
		lst.add("Please take me to the airport.");
		lst.add("That way.");
		lst.add("The plane departs at 5:30P.");
		lst.add("They arrived yesterday.");
		lst.add("Turn around.");
		lst.add("Turn left.");
		lst.add("Turn right.");
		lst.add("What time are you going to the bus station?");
		lst.add("When did this happen?");
		lst.add("When did you arrive in Boston?");
		lst.add("When does he arrive?");
		lst.add("When does it arrive?");
		lst.add("When does the bank open?");
		lst.add("When does the bus leave?");
		lst.add("When do we arrive?");
		lst.add("When do we leave?");
		lst.add("Where can I mail this?");
		lst.add("Where is she from?");
		lst.add("Where is the bathroom?");
		lst.add("Why not?");
		lst.add("Will you remind me?");
		lst.add("11 dollars.");
		lst.add("52 cents.");
		lst.add("A few.");
		lst.add("A little.");
		lst.add("Call the police.");
		lst.add("Did your wife like California?");
		lst.add("Do you have any coffee?");
		lst.add("Do you have anything cheaper?");
		lst.add("Do you take credit cards?");
		lst.add("How are you paying?");
		lst.add("How many people are there in New York?");
		lst.add("How much are these earrings?");
		lst.add("How much does it cost per day?");
		lst.add("How much does this cost?");
		lst.add("How much do I owe you?");
		lst.add("How much is it to go to Miami?");
		lst.add("How much money do you make?");
		lst.add("I'd like to eat at 5th street restaurant.");
		lst.add("I don't have a girlfriend.");
		lst.add("I don't have any money.");
		lst.add("I have a reservation.");
		lst.add("I'll have the same thing.");
		lst.add("I'll pay for dinner.");
		lst.add("I'll pay for the tickets.");
		lst.add("I'm 26 years old.");
		lst.add("I need to practice my English.");
		lst.add("Isn't it?");
		lst.add("Is that ok?");
		lst.add("Is there any mail for me?");
		lst.add("It's 11:30pm.");
		lst.add("It's is a quarter past nine.");
		lst.add("Please come in.");
		lst.add("Sorry, we don't accept credit cards.");
		lst.add("Sorry, we only accept Cash.");
		lst.add("That restaurant is not expensive.");
		lst.add("That's too expensive.");
		lst.add("There are many people here.");
		lst.add("They charge 26 dollars per day.");
		lst.add("What's the exchange rate for dollars?");
		lst.add("What's the phone number?");
		lst.add("Where can I buy tickets?");
		lst.add("Where would you like to meet?");
		lst.add("Which one is better?");
		lst.add("Across from the post office.");
		lst.add("At 3 o'clock.");
		lst.add("Be quiet.");
		lst.add("Can you recommend a good restaurant?");
		lst.add("Here it is.");
		lst.add("Here you are.");
		lst.add("He's in the kitchen.");
		lst.add("He studies at Boston University.");
		lst.add("How far is it?");
		lst.add("How far is it to Chicago?");
		lst.add("How many miles is it to Pennsylvania?");
		lst.add("I'd like a single room.");
		lst.add("I like to watch TV.");
		lst.add("It's delicious!");
		lst.add("It's half past 11.");
		lst.add("It's less than 5 dollars.");
		lst.add("It's more than 5 dollars.");
		lst.add("It's near the Supermarket.");
		lst.add("it's not suppose to rain today.");
		lst.add("It's ok.");
		lst.add("It's on 7th street.");
		lst.add("It's really hot.");
		lst.add("It's suppose to rain tomorrow.");
		lst.add("I was going to the library.");
		lst.add("I was in the library.");
		lst.add("Let's go.");
		lst.add("Maybe.");
		lst.add("More than 200 miles.");
		lst.add("My house is close to the bank.");
		lst.add("Near the bank.");
		lst.add("On the left.");
		lst.add("On the right.");
		lst.add("On the second floor.");
		lst.add("Outside the hotel.");
		lst.add("Over here.");
		lst.add("Over there.");
		lst.add("The book is behind the table.");
		lst.add("The book is in front of the table.");
		lst.add("The book is near the table.");
		lst.add("The book is next to the table.");
		lst.add("The book is on top of the table.");
		lst.add("There are some books on the table.");
		lst.add("There's a book under the table.");
		lst.add("We're from California.");
		lst.add("What's the address?");
		lst.add("Where are you going?");
		lst.add("Where is it?");
		lst.add("Where would you like to go?");
		lst.add("Who won?");
		lst.add("Can I see your passport please?");
		lst.add("Can I take a message?");
		lst.add("Can I try it on?");
		lst.add("Can we sit over there?");
		lst.add("Did you come with your family?");
		lst.add("Do you think it's possible?");
		lst.add("Here's my number.");
		lst.add("He's not in right now.");
		lst.add("Hi, is Mrs. Smith there, please?");
		lst.add("I'd like some water too, please.");
		lst.add("I'd like to buy a bottle of water, please.");
		lst.add("I'd like to buy something.");
		lst.add("I'd like to go to the store.");
		lst.add("I'd like to rent a car.");
		lst.add("I'd like to send a fax.");
		lst.add("I'd like to send this to America.");
		lst.add("I'd like to speak to Mr. Smith please.");
		lst.add("I have three children, two girls and one boy.");
		lst.add("I'll be right back.");
		lst.add("I'll call back later.");
		lst.add("I'll call you on Friday.");
		lst.add("I'll teach you.");
		lst.add("I'm ok.");
		lst.add("I need some tissues.");
		lst.add("Is there an English speaking guide?");
		lst.add("I want to give you a gift.");
		lst.add("Male or female?");
		lst.add("My cell phone doesn't have good reception.");
		lst.add("My cell phone doesn't work.");
		lst.add("Please take off your shoes.");
		lst.add("Sorry, I think I have the wrong number.");
		lst.add("What is the area code?");
		lst.add("What's the name of the company you work for?");
		lst.add("What's wrong?");
		lst.add("What's your address?");
		lst.add("Where can I find a hospital?");
		lst.add("Where's the closest restaurant?");
		lst.add("Where's the pharmacy?");
		lst.add("Who are you?");
		lst.add("Who is that?");
		lst.add("Who would you like to speak to?");
		lst.add("Will you take me home?");
		lst.add("Would you like water or milk?");
		lst.add("11 days ago.");
		lst.add("2 hours.");
		lst.add("All day.");
		lst.add("A long time ago.");
		lst.add("Are they coming this evening?");
		lst.add("Are you comfortable?");
		lst.add("Are your children with you?");
		lst.add("As soon as possible.");
		lst.add("At 3 o'clock in the afternoon.");
		lst.add("At 5th street.");
		lst.add("At 7 o'clock at night. (evening)?");
		lst.add("At 7 o'clock in the morning.");
		lst.add("At what time did it happen?");
		lst.add("Can I help you?");
		lst.add("Do you have a swimming pool?");
		lst.add("Do you have this in size 11?");
		lst.add("Do you think you'll be back by 11:30?");
		lst.add("Everyday I get up at 6AM.");
		lst.add("Every week.");
		lst.add("Expiration date.");
		lst.add("Have you been waiting long?");
		lst.add("He'll be back in 20 minutes.");
		lst.add("His family is coming tomorrow.");
		lst.add("How about Saturday?");
		lst.add("How long are you going to stay?");
		lst.add("How long are you going to stay in California?");
		lst.add("How long will it take?");
		lst.add("How much altogether?");
		lst.add("How much will it cost?");
		lst.add("I don't have enough money.");
		lst.add("I'm getting ready to go out.");
		lst.add("I'm just looking. (Shopping)");
		lst.add("I'm worried too.");
		lst.add("It'll be cold this evening.");
		lst.add("It rained very hard today.");
		lst.add("It's 17 dollars.");
		lst.add("It's 6AM.");
		lst.add("It's 8:45.");
		lst.add("It's a quarter to 7.");
		lst.add("It's going to snow today.");
		lst.add("It's here.");
		lst.add("It's there.");
		lst.add("I've already seen it.");
		lst.add("John is going on vacation tomorrow.");
		lst.add("My birthday is August 27th.");
		lst.add("Now or later?");
		lst.add("October 22nd.");
		lst.add("She wants to know when you're coming.");
		lst.add("Sometimes I go to sleep at 11PM, sometimes at 11:30PM.");
		lst.add("There's plenty of time.");
		lst.add("The whole day.");
		lst.add("We're late.");
		lst.add("What day are they coming over?");
		lst.add("What day of the week is it?");
		lst.add("What is today's date?");
		lst.add("What's your religion?");
		lst.add("What time are they arriving?");
		lst.add("What time did you get up?");
		lst.add("What time did you go to sleep?");
		lst.add("What time did you wake up?");
		lst.add("What time does it start?");
		lst.add("What time do you think you'll arrive?");
		lst.add("What time is it?");
		lst.add("When are they coming?");
		lst.add("When are you coming back?");
		lst.add("When are you going to pick up your friend?");
		lst.add("When are you leaving?");
		lst.add("When are you moving?");
		lst.add("When is the next bus to Philidalphia?");
		lst.add("When is your birthday?");
		lst.add("When I went to the store, they didn't have any apples.");
		lst.add("When was the last time you talked to your mother?");
		lst.add("When will he be back?");
		lst.add("When will it be ready?");
		lst.add("Where are you going to go?");
		lst.add("Are you busy?");
		lst.add("Can we have some more bread please?");
		lst.add("Do you have any money?");
		lst.add("For how many nights?");
		lst.add("How long will you be staying?");
		lst.add("I'd like a map of the city.");
		lst.add("I'd like a fresh newspaper.");
		lst.add("I'd like a room.");
		lst.add("I'd like a room with two beds please.");
		lst.add("I need a doctor.");
		lst.add("Is there a nightclub in town?");
		lst.add("Is there a restaurant in the hotel?");
		lst.add("Is there a store near here?");
		lst.add("Sorry, we don't have any vacancies.");
		lst.add("Take me to the Marriott Hotel.");
		lst.add("What's the charge per night? (Hotel)");
		lst.add("What time is check out?");
		lst.add("Where is the airport?");
		lst.add("Where's the mail box?");
		lst.add("Are you here alone?");
		lst.add("Can I bring my friend?");
		lst.add("Can I have a receipt please?");
		lst.add("Can it be cheaper?");
		lst.add("Can we have a menu please.");
		lst.add("Can you hold this for me?");
		lst.add("Do you have any children?");
		lst.add("Do you know how much it costs?");
		lst.add("Have you eaten at that restaurant?");
		lst.add("Have you eaten yet?");
		lst.add("Have you ever had Potato soup?");
		lst.add("He likes juice but he doesn't like milk");
		lst.add("Here is your salad.");
		lst.add("Here's your order.");
		lst.add("How does it taste?");
		lst.add("How many people? (restaurant)");
		lst.add("I agree.");
		lst.add("I'd like a table near the window.");
		lst.add("I'd like to call the United States.");
		lst.add("I haven't been there.");
		lst.add("I haven't finished eating.");
		lst.add("I like it.");
		lst.add("I'll give you a call.");
		lst.add("I'll have a cup of tea please.");
		lst.add("I'll have a glass of water please.");
		lst.add("I'm from America.");
		lst.add("I'm going to bed.");
		lst.add("I'm here on business.");
		lst.add("I'm sorry.");
		lst.add("I only have 5 dollars.");
		lst.add("I think I need to see a doctor.");
		lst.add("It's August 25th.");
		lst.add("I understand.");
		lst.add("June 3rd.");
		lst.add("The food was delicious.");
		lst.add("There are some apples in the refrigerator.");
		lst.add("There's a restaurant near here.");
		lst.add("There's a restaurant over there, but I don't think it's very good.");
		lst.add("Waiter!");
		lst.add("Waitress!");
		lst.add("We can eat Italian or Chinese food.");
		lst.add("We'll have two glasses of water please.");
		lst.add("What are you going to have?");
		lst.add("What do you recommend?");
		lst.add("What's your email address?");
		lst.add("What would you like to drink?");
		lst.add("What would you like to eat?");
		lst.add("Where is an ATM?");
		lst.add("Where is there a doctor who speaks English?");
		lst.add("Which one?");
		lst.add("Would you ask him to come here?");
		lst.add("Would you like a glass of water?");
		lst.add("Would you like coffee or tea?");
		lst.add("Would you like something to drink?");
		lst.add("Would you like some water?");
		lst.add("Would you like some juice?");
		lst.add("Would you like to go for a walk?");
		lst.add("Would you like to watch TV?");
		lst.add("Are you American?");
		lst.add("Are you coming this evening?");
		lst.add("Are you free tonight?");
		lst.add("Are you going to take a plane or train?");
		lst.add("Are you hungry?");
		lst.add("Are you sure?");
		lst.add("Are you working Tomorrow?");
		lst.add("Business is good.");
		lst.add("Cheers!");
		lst.add("Did it snow yesterday?");
		lst.add("Did you get my email?");
		lst.add("Did you take your medicine?");
		lst.add("Do you feel better?");
		lst.add("Do you go to Florida often?");
		lst.add("Do you have another one?");
		lst.add("Do you know where there's a store that sells towels?");
		lst.add("Do you like it here?");
		lst.add("Do you like the book?");
		lst.add("Do you need anything?");
		lst.add("Do you play any sports?");
		lst.add("Do you sell medicine? (store)");
		lst.add("Do you study English?");
		lst.add("Do you want to come with me?");
		lst.add("Do you want to go with me?");
		lst.add("Excuse me.");
		lst.add("Give me a call.");
		lst.add("Has your brother been to California?");
		lst.add("Have they met her yet?");
		lst.add("Have you done this before?");
		lst.add("How long have you been here?");
		lst.add("How long have you been in America?");
		lst.add("How long have you lived here?");
		lst.add("How many children do you have?");
		lst.add("How many languages do you speak?");
		lst.add("How many people do you have in your family?");
		lst.add("How much would you like?");
		lst.add("How old are you?");
		lst.add("I bought a shirt yesterday.");
		lst.add("I don't feel well.");
		lst.add("I have pain in my arm.");
		lst.add("I have to wash my clothes.");
		lst.add("I have two sisters.");
		lst.add("I'll tell him you called.");
		lst.add("I'm 32.");
		lst.add("I'm allergic to seafood.");
		lst.add("I'm American.");
		lst.add("I'm a size 8.");
		lst.add("I'm fine, and you?");
		lst.add("I'm not afraid.");
		lst.add("I'm sick.");
		lst.add("I remember.");
		lst.add("I speak a little English.");
		lst.add("Is your house like this one?");
		lst.add("Is your husband also from Boston?");
		lst.add("It's not very expensive.");
		lst.add("I've been there.");
		lst.add("Let's share.");
		lst.add("My daughter is here.");
		lst.add("My father has been there.");
		lst.add("My father is a lawyer.");
		lst.add("My grandmother passed away last year.");
		lst.add("My name is John Smith.");
		lst.add("My son.");
		lst.add("My son studies computers.");
		lst.add("No, I'm American.");
		lst.add("No, this is the first time.");
		lst.add("Our children are in America.");
		lst.add("She's an expert.");
		lst.add("She's older than me.");
		lst.add("That car is similar to my car.");
		lst.add("This is Mrs. Smith.");
		lst.add("This is my mother.");
		lst.add("This is the first time I've been here.");
		lst.add("We have two boys and one girl.");
		lst.add("What are you going to do tonight?");
		lst.add("What are your hobbies?");
		lst.add("What do you study?");
		lst.add("What do you want to do?");
		lst.add("What school did you go to?");
		lst.add("What's your favorite movie?");
		lst.add("What's your last name?");
		lst.add("What's your name?");
		lst.add("Where are the t-shirts?");
		lst.add("Where did you go?");
		lst.add("Where did you learn English?");
		lst.add("Where did you work before you worked here?");
		lst.add("Where do you live?");
		lst.add("Where were you?");
		lst.add("Who sent this letter?");
		lst.add("Would you like to buy this?");
		lst.add("Your children are very well behaved.");
		lst.add("Your daughter.");
		lst.add("You're smarter than him.");
		lst.add("You speak English very well.");
		lst.add("Are there any concerts?");
		lst.add("Do you want to go to the movies?");
		lst.add("Have you seen this movie?");
		lst.add("He said you like to watch movies.");
		lst.add("How tall are you?");
		lst.add("Is the bank far?");
		lst.add("Is there a movie theater nearby?");
		lst.add("What do people usually do in the summer in Los Angeles?");
		lst.add("What kind of music do you like?");
		lst.add("What's your favorite food?");
		lst.add("What time does the movie start?");
		lst.add("Who was your teacher?");
		lst.add("Would you like to have dinner with me?");
		lst.add("Would you like to rent a movie?");
		lst.add("Can I have a glass of water please?");
		lst.add("Can I use your phone?");
		lst.add("Do you have any vacancies?");
		lst.add("Do you have the number for a taxi?");
		lst.add("Do you know her?");
		lst.add("Do you know where she is?");
		lst.add("Do you play basketball?");
		lst.add("Fill it up, please. (gas station)");
		lst.add("He needs some new clothes.");
		lst.add("How much is that?");
		lst.add("How much is this?");
		lst.add("I believe you.");
		lst.add("I'd like the number for the Hilton Hotel please.");
		lst.add("I'd like to buy a phone card please.");
		lst.add("I'd like to go home.");
		lst.add("I'd like to go shopping.");
		lst.add("If you like it I can buy more.");
		lst.add("I'm a beginner.");
		lst.add("I'm full.");
		lst.add("I'm just kidding.");
		lst.add("I'm single.");
		lst.add("I speak two languages.");
		lst.add("I thought he said something else.");
		lst.add("It's not too far.");
		lst.add("I usually drink coffee at breakfast.");
		lst.add("Sorry, we don't have any.");
		lst.add("The books are expensive.");
		lst.add("Try it on.");
		lst.add("What do you want to buy?");
		lst.add("What size?");
		lst.add("What time does the store open?");
		lst.add("When does the plane arrive?");
		lst.add("Where are you?");
		lst.add("Would you like something to eat?");
		lst.add("Am I pronouncing it correctly?");
		lst.add("Can you do me a favor?");
		lst.add("Can you help me?");
		lst.add("Can you please say that again?");
		lst.add("Can you show me?");
		lst.add("Can you throw that away for me?");
		lst.add("Does anyone here speak English?");
		lst.add("Don't do that.");
		lst.add("Do you believe that?");
		lst.add("Do you have a pencil?");
		lst.add("Do you want a cup of tea?");
		lst.add("Do you speak English?");
		lst.add("Excuse me, what did you say?");
		lst.add("Forget it.");
		lst.add("How do you pronounce that?");
		lst.add("How do you say it in English?");
		lst.add("How do you spell it?");
		lst.add("How do you spell the word 'Seattle'?");
		lst.add("I can swim.");
		lst.add("I can't hear you clearly.");
		lst.add("I don't mind.");
		lst.add("I don't speak English very well.");
		lst.add("I don't think so.");
		lst.add("I don't understand what your saying.");
		lst.add("Is there air conditioning in the room?");
		lst.add("I think you have too many clothes.");
		lst.add("I trust you.");
		lst.add("I understand now.");
		lst.add("Let's meet in front of the hotel.");
		lst.add("Please sit down.");
		lst.add("Please speak English.");
		lst.add("Please speak more slowly.");
		lst.add("Sorry, I didn't hear clearly.");
		lst.add("That means friend.");
		lst.add("That's wrong.");
		lst.add("Try to say it.");
		lst.add("What does this mean?");
		lst.add("What does this say?");
		lst.add("What does this word mean?");
		lst.add("What's the exchange rate?");
		lst.add("Whose book is that?");
		lst.add("Why aren't you going?");
		lst.add("Why are you laughing?");
		lst.add("Why did you do that?");
		lst.add("Are you allergic to anything?");
		lst.add("Are you ready?");
		lst.add("Call me.");
		lst.add("Did you send me flowers?");
		lst.add("Do you sell batteries?");
		lst.add("I don't care.");
		lst.add("I give up.");
		lst.add("I got in an accident.");
		lst.add("I have a cold.");
		lst.add("I have one in my car.");
		lst.add("I made this cake.");
		lst.add("I'm a teacher.");
		lst.add("I'm self-employed.");
		lst.add("I still have a lot to do.");
		lst.add("I still haven't decided.");
		lst.add("It depends on the weather.");
		lst.add("It's very cold today.");
		lst.add("My luggage is missing.");
		lst.add("My stomach hurts.");
		lst.add("My throat is sore.");
		lst.add("My watch has been stolen.");
		lst.add("Take this medicine.");
		lst.add("The accident happened at the intersection.");
		lst.add("There has been a car accident.");
		lst.add("Where can I exchange U.S. dollars?");
		lst.add("Where do you work?");
		lst.add("Where's the nearest hospital?");
		lst.add("Where's the post office?");
		lst.add("And you?");
		lst.add("Anything else?");
		lst.add("Are they the same?");
		lst.add("Are you afraid?");
		lst.add("Are you going to attend their wedding?");
		lst.add("Are you married?");
		lst.add("Are you okay?");
		lst.add("Are you sick?");
		lst.add("Behind the bank.");
		lst.add("Can I borrow some money?");
		lst.add("Can I have the bill please?");
		lst.add("Can you call back later?");
		lst.add("Can you call me back later?");
		lst.add("Can you carry this for me?");
		lst.add("Can you fix this?");
		lst.add("Can you give me an example?");
		lst.add("Can you speak louder please?");
		lst.add("Can you swim?");
		lst.add("Does he like the school?");
		lst.add("Do you accept U.S. Dollars?");
		lst.add("Do you have a girlfriend?");
		lst.add("Do you have an appointment?");
		lst.add("Do you have a problem?");
		lst.add("Do you hear that?");
		lst.add("Do you know how to get to the Marriott Hotel?");
		lst.add("Do you know what this means?");
		lst.add("Do you know where I can get a taxi?");
		lst.add("Do you know where my glasses are?");
		lst.add("Do you like your co-workers?");
		lst.add("Do you need anything else?");
		lst.add("Do you understand?");
		lst.add("Give me the pen.");
		lst.add("How do you know?");
		lst.add("How is she?");
		lst.add("How long is it?");
		lst.add("How many?");
		lst.add("How much is it?");
		lst.add("I have a lot of things to do.");
		lst.add("In 30 minutes.");
		lst.add("Is anyone else coming?");
		lst.add("Is everything ok?");
		lst.add("Is it cold outside?");
		lst.add("Is it far from here?");
		lst.add("Is it hot?");
		lst.add("Is it raining?");
		lst.add("Is there anything cheaper?");
		lst.add("Is your son here?");
		lst.add("Should I wait?");
		lst.add("The big one or the small one?");
		lst.add("The cars are American.");
		lst.add("Were there any problems?");
		lst.add("Were you at the library last night?");
		lst.add("What are you doing?");
		lst.add("What are you thinking about?");
		lst.add("What are you two talking about?");
		lst.add("What did you do last night?");
		lst.add("What did you do yesterday?");
		lst.add("What did you think?");
		lst.add("What do they study?");
		lst.add("What do you have?");
		lst.add("What do you think?");
		lst.add("What happened?");
		lst.add("What is it?");
		lst.add("What is that?");
		lst.add("What should I wear?");
		lst.add("What's in it?");
		lst.add("What's the temperature?");
		lst.add("What's this?");
		lst.add("What's up?");
		lst.add("Where are you from?");
		lst.add("Where can I rent a car?");
		lst.add("Where did it happen?");
		lst.add("Where did you learn it?");
		lst.add("Where is he?");
		lst.add("Where is he from?");
		lst.add("Which is better, the spaghetti or chicken salad?");
		lst.add("Which one do you want?");
		lst.add("Which one is cheaper?");
		lst.add("Which one is the best?");
		lst.add("Which school does he go to?");
		lst.add("Who are they?");
		lst.add("Who are you looking for?");
		lst.add("Who is it?");
		lst.add("Who's calling?");
		lst.add("Who's that man over there?");
		lst.add("Who taught you that?");
		lst.add("Why did you say that?");
		lst.add("Will you pass me the salt please?");
		lst.add("Will you put this in the car for me?");
		lst.add("Would you ask him to call me back please?");
		lst.add("You have a very nice car.");
		lst.add("You look like my sister.");
		lst.add("6 dollars per hour.");
		lst.add("Are you waiting for someone?");
		lst.add("Are you working today?");
		lst.add("Bring me my shirt please.");
		lst.add("Do you like to watch TV?");
		lst.add("Do you like your boss?");
		lst.add("Have you finished studying?");
		lst.add("He's an Engineer.");
		lst.add("He's very hard working.");
		lst.add("He works at a computer company in New York.");
		lst.add("How long have you worked here?");
		lst.add("How many hours a week do you work?");
		lst.add("How much money do you have?");
		lst.add("How's the weather?");
		lst.add("How was the trip?");
		lst.add("I forget.");
		lst.add("I'm good.");
		lst.add("I'm ready.");
		lst.add("I still have a lot of things to buy.");
		lst.add("I've seen it.");
		lst.add("What does he do for work?");
		lst.add("What does your father do for work?");
		lst.add("What do you do for work?");
		lst.add("What do your parents do for work?");
		lst.add("What's the matter?");
		lst.add("What time do you go to work everyday?");
		lst.add("When do you arrive in the U.S.?");
		lst.add("When do you get off work?");
		lst.add("Where did you put it?");
		lst.add("Where does it hurt?");
		lst.add("Where do you want to go?");
		lst.add("Come here.");
		lst.add("Does it often snow in the winter in Massachusetts?");
		lst.add("Do you think it'll rain today?");
		lst.add("Do you think it's going to rain tomorrow?");
		lst.add("How's business?");
		lst.add("Is it close?");
		lst.add("Is it possible?");
		lst.add("Is it ready?");
		lst.add("It costs 20 dollars per hour.");
		lst.add("It hurts here.");
		lst.add("It's far from here.");
		lst.add("It's going to be hot today.");
		lst.add("It's north of here.");
		lst.add("It's over there.");
		lst.add("It's raining.");
		lst.add("It's too late.");
		lst.add("It's very important.");
		lst.add("It will arrive shortly.");
		lst.add("The roads are slippery.");
		lst.add("What's the room rate?");
		lst.add("What will the weather be like tomorrow?");
		lst.add("Amy is John's girlfriend.");
		lst.add("He always does that for me.");
		lst.add("He broke the window.");
		lst.add("He doesn't look like a nurse.");
		lst.add("He has a nice car.");
		lst.add("He never gives me anything.");
		lst.add("He said this is a nice place.");
		lst.add("He's an American.");
		lst.add("He's a very good student.");
		lst.add("He's faster than me.");
		lst.add("He thinks we don't want to go.");
		lst.add("His room is very small.");
		lst.add("His son.");
		lst.add("How are your parents?");
		lst.add("How do I use this?");
		lst.add("I came with my family.");
		lst.add("I'd like to exchange this for Dollars.");
		lst.add("I'd like to use the internet");
		lst.add("I don't have time right now.");
		lst.add("I don't know.");
		lst.add("I have money.");
		lst.add("I haven't had lunch yet.");
		lst.add("I have to go to the post office.");
		lst.add("I like Italian food.");
		lst.add("I live in California.");
		lst.add("I'll talk to you soon.");
		lst.add("I made a mistake.");
		lst.add("I'm bored.");
		lst.add("I'm going to America next year.");
		lst.add("I'm going to go have dinner.");
		lst.add("I'm tired.");
		lst.add("I'm very well, thank you.");
		lst.add("I need another key.");
		lst.add("I need this to get there by tomorrow.");
		lst.add("I need to go now.");
		lst.add("Is it suppose to rain tomorrow?");
		lst.add("Is John there please? (phone call)");
		lst.add("Is this a safe area?");
		lst.add("Is this Mr. Smith?");
		lst.add("Is this the bus to New York?");
		lst.add("Is this your book?");
		lst.add("I still have to brush my teeth and take a shower.");
		lst.add("Is your father home?");
		lst.add("I think so.");
		lst.add("I think those shoes are very good looking.");
		lst.add("It's very windy.");
		lst.add("It takes 2 hours by car.");
		lst.add("I've never done that.");
		lst.add("I've worked there for five years.");
		lst.add("I want to buy something.");
		lst.add("I want to contact our embassy.");
		lst.add("I want to send this package to the United States.");
		lst.add("I want to show you something.");
		lst.add("I went to the supermarket, and then to the computer store.");
		lst.add("My car isn't working.");
		lst.add("Nobody is helping us.");
		lst.add("Nobody is there right now.");
		lst.add("One like that.");
		lst.add("Open the door.");
		lst.add("Open the window.");
		lst.add("Pick up your clothes.");
		lst.add("Please.");
		lst.add("Please count this for me.");
		lst.add("Please tell her John called.");
		lst.add("Please tell me.");
		lst.add("Please wait for me.");
		lst.add("She's going with me tomorrow.");
		lst.add("Some books.");
		lst.add("Someone does that for me.");
		lst.add("Someone is coming.");
		lst.add("Sorry, I don't have a pencil.");
		lst.add("Start the car.");
		lst.add("Take me downtown.");
		lst.add("Tell him that I need to talk to him.");
		lst.add("That car over there is mine.");
		lst.add("That looks old.");
		lst.add("That's a good school.");
		lst.add("That's her book.");
		lst.add("That's not enough.");
		lst.add("The car is fixed.");
		lst.add("These books are ours.");
		lst.add("The TV is broken.");
		lst.add("They haven't met her yet.");
		lst.add("They're planning to come next year.");
		lst.add("They're waiting for us.");
		lst.add("This room is a mess.");
		lst.add("Those men are speaking English.");
		lst.add("What color is that car?");
		lst.add("What do you think of these shoes?");
		lst.add("When would you like to meet?");
		lst.add("Where does your wife work?");
		lst.add("Where is Main Street?");
		lst.add("Where is my shirt?");
		lst.add("Where is the bus station?");
		lst.add("Which road should I take?");
		lst.add("You're right.");
		lst.add("Your house is very nice.");
		return lst;
	}
}